import type { Hostel } from "@shared/schema";

export const mockHostels: Hostel[] = [
  {
    id: 1,
    name: "University Gardens Hostel",
    description: "Modern hostel with spacious rooms, 24/7 security, and excellent facilities. Perfect for serious students.",
    university: "Makerere University",
    distance: "0.8km from Makerere University",
    price: 300000,
    rating: "4.8",
    reviewCount: 24,
    imageUrl: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    amenities: ["WiFi", "Security", "Kitchen", "Laundry"],
    contact: "+256 700 123456",
    address: "Wandegeya, Kampala",
    available: true,
    createdAt: new Date(),
  },
  {
    id: 2,
    name: "Scholars Inn",
    description: "Affordable accommodation with dedicated study areas and quiet environment ideal for academic focus.",
    university: "Makerere University",
    distance: "1.2km from Makerere University",
    price: 250000,
    rating: "4.3",
    reviewCount: 18,
    imageUrl: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    amenities: ["WiFi", "Study Rooms", "Parking"],
    contact: "+256 700 789012",
    address: "Kikoni, Kampala",
    available: true,
    createdAt: new Date(),
  },
  {
    id: 3,
    name: "Campus View Hostel",
    description: "Premium accommodation with air conditioning, gym facilities, and stunning campus views.",
    university: "Makerere University",
    distance: "0.5km from Makerere University",
    price: 400000,
    rating: "4.9",
    reviewCount: 31,
    imageUrl: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=600",
    amenities: ["Premium", "AC", "Gym", "WiFi"],
    contact: "+256 700 345678",
    address: "Makerere Hill, Kampala",
    available: true,
    createdAt: new Date(),
  },
];
