#!/usr/bin/env python3
"""Append all remaining view functions to hostels/views.py"""
import os, py_compile
os.chdir('c:/Users/user/ehostelfinder')

lines = []
def L(s, indent=0):
    if indent:
        s = '    ' * indent + s
    lines.append(s)

# ===== API ENDPOINTS =====
L('')
L('@require_http_methods(["GET"])')
L('def api_hostels(request):')
L(1, 'city = request.GET.get("city", ""); country = request.GET.get("country", "")')
L(1, 'room_type = request.GET.get("room_type", ""); university = request.GET.get("university", "")')
L(1, 'min_price = request.GET.get("min_price", ""); max_price = request.GET.get("max_price", "")')
L(1, 'hostels = Hostel.objects.all()')
L(1, 'if city: hostels = hostels.filter(city__icontains=city)')
L(1, 'if country: hostels = hostels.filter(country__icontains=country)')
L(1, 'if university: hostels = hostels.filter(university=university)')
L(1, 'if room_type: hostels = hostels.filter(rooms__room_type=room_type).distinct()')
L(1, 'if min_price:')
L(2, 'try: hostels = hostels.filter(price__gte=float(min_price)).distinct()')
L(2, 'except: pass')
L(1, 'if max_price:')
L(2, 'try: hostels = hostels.filter(price__lte=float(max_price)).distinct()')
L(2, 'except: pass')
L(1, 'results = []')
L(1, 'for h in hostels:')
L(2, 'cover = h.images.filter(is_cover=True).first()')
L(2, 'results.append({"id": str(h.id), "name": h.name, "city": h.city, "country": h.country, "university": h.university, "address": h.address, "description": h.description, "average_rating": round(float(h.average_rating), 2), "rating": float(h.rating) if h.rating else round(float(h.average_rating), 2), "review_count": h.reviews.count(), "image_url": h.image_url or (cover.image_url if cover else None), "facilities": [f.facility_name for f in h.facilities.all()], "amenities": h.amenities or [], "distance": h.distance or "", "price": float(h.price) if h.price else 0, "contact": h.contact or "", "available": h.available})')
L(1, 'return JsonResponse(results, safe=False)')
L('')
L('@require_http_methods(["GET"])')
L('def api_hostel_detail(request, id):')
L(1, 'hostel = get_object_or_404(Hostel, id=id)')
L(1, 'rooms = Room.objects.filter(hostel=hostel)')
L(1, 'cover = hostel.images.filter(is_cover=True).first()')
L(1, 'rooms_data = [{"id": str(r.id), "room_number": r.room_number, "room_name": r.room_name, "room_type": r.room_type, "capacity": r.capacity, "price_per_night": str(r.price_per_night), "description": r.description, "private_bathroom": r.private_bathroom, "air_conditioning": r.air_conditioning, "wifi": r.wifi, "status": r.status} for r in rooms]')
L(1, 'return JsonResponse({"id": str(hostel.id), "name": hostel.name, "description": hostel.description, "address": hostel.address, "city": hostel.city, "country": hostel.country, "phone": hostel.phone, "email": hostel.email, "latitude": str(hostel.latitude) if hostel.latitude else None, "longitude": str(hostel.longitude) if hostel.longitude else None, "image_url": cover.image_url if cover else None, "rooms": rooms_data, "facilities": [{"name": f.facility_name} for f in hostel.facilities.all()]})')
L('')
L('@require_http_methods(["GET"])')
L('def api_cities(request):')
L(1, 'return JsonResponse(sorted(Hostel.objects.values_list("city", flat=True).exclude(city="").distinct()), safe=False)')
L('')
L('@require_http_methods(["GET"])')
L('def api_countries(request):')
L(1, 'return JsonResponse(sorted(Hostel.objects.values_list("country", flat=True).exclude(country="").distinct()), safe=False)')
L('')

# ===== AUTH =====
L('@require_http_methods(["GET", "POST"])')
L('def login(request):')
L(1, 'if request.method == "GET":')
L(2, 'return render(request, "login.html", {"form": UserLoginForm()})')
L(1, 'form = UserLoginForm(request.POST)')
L(1, 'if form.is_valid():')
L(2, 'from django.contrib.auth import authenticate, login as auth_login')
L(2, 'user = authenticate(request, username=form.cleaned_data["email"], password=form.cleaned_data["password"])')
L(2, 'if user:')
L(3, 'auth_login(request, user)')
L(3, 'return redirect("home")')
L(2, 'messages.error(request, "Invalid email or password")')
L(1, 'else:')
L(2, 'messages.error(request, "Invalid email or password")')
L(1, 'return render(request, "login.html", {"form": form})')
L('')
L('@require_http_methods(["GET", "POST"])')
L('def signup(request):')
L(1, 'if request.method == "POST":')
L(2, 'form = UserRegistrationForm(request.POST)')
L(2, 'if form.is_valid():')
L(3, 'user = form.save()')
L(3, 'try:')
L(4, 'from .email_utils import send_email_confirmation')
L(4, 'send_email_confirmation(user, request)')
L(3, 'except Exception:')
L(4, 'pass')
L(3, 'messages.success(request, "Account created! Please check your email to confirm.")')
L(3, 'return redirect("login")')
L(1, 'else:')
L(2, 'form = UserRegistrationForm()')
L(1, 'return render(request, "signup.html", {"form": form})')
L('')
L('@require_http_methods(["GET"])')
L('def logout_view(request):')
L(1, 'logout(request)')
L(1, 'return redirect("home")')
L('')
L('def cookie_policy(request):')
L(1, 'return render(request, "cookie_policy.html")')
L('')
L('def privacy_policy(request):')
L(1, 'return render(request, "privacy_policy.html")')
L('')
L('def terms_of_use(request):')
L(1, 'return render(request, "terms_of_use.html")')
L('')
L('def ai_assistant(request):')
L(1, 'return render(request, "ai_assistant.html")')
L('')
L('def how_it_works(request):')
L(1, 'return render(request, "how_it_works.html")')
L('')

# ===== ADMIN MESSAGES =====
L('@require_http_methods(["GET"])')
L('def admin_messages(request):')
L(1, 'if not request.user.is_authenticated:')
L(2, 'return JsonResponse({"error": "Auth required"}, status=401)')
L(1, 'msgs = ContactMessage.objects.all()[:100]')
L(1, 'return JsonResponse({"messages": [')
L(2, '{"id": msg.id, "full_name": msg.full_name, "email": msg.email,')
L(2, '"subject": msg.subject, "message": msg.message,')
L(2, '"created_at": msg.created_at.isoformat(), "is_read": msg.is_read}')
L(2, 'for msg in msgs')
L(1, ']})')
L('')
L('@require_http_methods(["GET", "POST"])')
L('def get_user(request):')
L(1, 'if request.user.is_authenticated:')
L(2, 'p = getattr(request.user, "profile", None)')
L(2, 'return JsonResponse({')
L(3, '"id": request.user.id, "email": request.user.email,')
L(3, '"first_name": request.user.first_name, "last_name": request.user.last_name,')
L(3, '"profile_image_url": p.profile_photo if p else None,')
L(3, '"role": p.role if p else "customer",')
L(3, '"full_name": p.full_name if p else "",')
L(2, '})')
L(1, 'return JsonResponse({"error": "Not authenticated"}, status=401)')
L('')

# ===== BOOKINGS =====
L('@require_http_methods(["POST"])')
L('def create_booking(request):')
L(1, 'if not request.user.is_authenticated:')
L(2, 'return JsonResponse({"error": "Auth required"}, status=401)')
L(1, 'try:')
L(2, 'data = json.loads(request.body)')
L(2, 'room = get_object_or_404(Room, id=data.get("room_id"))')
L(2, 'from datetime import datetime')
L(2, 'check_in = datetime.strptime(data.get("check_in"), "%Y-%m-%d").date()')
L(2, 'check_out = datetime.strptime(data.get("check_out"), "%Y-%m-%d").date()')
L(2, 'guests = int(data.get("guests", 1))')
L(2, 'nights = (check_out - check_in).days')
L(2, 'if nights <= 0:')
L(3, 'return JsonResponse({"error": "Invalid date range"}, status=400)')
L(2, 'total_price = room.price_per_night * nights')
L(2, 'booking = Booking.objects.create(')
L(3, 'hostel_id=room.hostel_id, room=room,')
L(3, 'customer_id=request.user.id,')
L(3, 'check_in=check_in, check_out=check_out,')
L(3, 'guests=guests, nights=nights,')
L(3, 'total_price=total_price,')
L(3, 'special_requests=data.get("special_requests", ""),')
L(3, 'booking_status="Pending", payment_status="Pending",')
L(2, ')')
L(2, 'Notification.objects.create(')
L(3, 'user=request.user, title="Booking Created",')
L(3, 'message=f"Booking at {room.hostel.name} (Ref: {booking.booking_reference}) created.")')
L(2, 'return JsonResponse({')
L(3, '"id": str(booking.id),')
L(3, '"booking_reference": booking.booking_reference,')
L(3, '"hostel_id": str(booking.hostel_id),')
L(3, '"room_id": str(booking.room_id),')
L(3, '"check_in": booking.check_in.isoformat(),')
L(3, '"check_out": booking.check_out.isoformat(),')
L(3, '"guests": booking.guests,')
L(3, '"nights": booking.nights,')
L(3, '"total_price": str(booking.total_price),')
L(3, '"booking_status": booking.booking_status,')
L(3, '"payment_status": booking.payment_status,')
L(3, '"special_requests": booking.special_requests,')
L(2, '}, status=201)')
L(1, 'except Exception as e:')
L(2, 'return JsonResponse({"error": str(e)}, status=400)')
L('')
L('@require_http_methods(["GET"])')
L('def get_booking_by_id(request, id):')
L(1, 'try:')
L(2, 'booking = get_object_or_404(Booking, id=id)')
L(2, 'if request.user.id == booking.customer_id:')
L(3, 'return JsonResponse({')
L(4, '"id": str(booking.id),')
L(4, '"booking_reference": booking.booking_reference,')
L(4, '"hostel_id": str(booking.hostel_id),')
L(4, '"room_id": str(booking.room_id),')
L(4, '"check_in": booking.check_in.isoformat(),')
L(4, '"check_out": booking.check_out.isoformat(),')
L(4, '"guests": booking.guests,')
L(4, '"nights": booking.nights,')
L(4, '"total_price": str(booking.total_price),')
L(4, '"booking_status": booking.booking_status,')
L(4, '"payment_status": booking.payment_status,')
L(4, '"special_requests": booking.special_requests,')
L(3, '})')
L(2, 'return JsonResponse({"error": "Not authorized"}, status=403)')
L(1, 'except Exception as e:')
L(2, 'return JsonResponse({"error": str(e)}, status=500)')
L('')

# ===== MESSAGES =====
L('@require_http_methods(["POST"])')
L('def create_message(request):')
L(1, 'try:')
L(2, 'data = json.loads(request.body)')
L(2, 'hostel = get_object_or_404(Hostel, id=data.get("hostelId"))')
L(2, 'msg = Message.objects.create(')
L(3, 'hostel=hostel,')
L(3, 'user=request.user if request.user.is_authenticated else None,')
L(3, 'full_name=data.get("fullName", ""),')
L(3, 'email=data.get("email", ""),')
L(3, 'phone=data.get("phone", ""),')
L(3, 'subject=data.get("subject", ""),')
L(3, 'content=data.get("content", "") or data.get("message", ""),')
L(2, ')')
L(2, 'return JsonResponse({')
L(3, '"id": str(msg.id), "hostel_id": str(msg.hostel_id),')
L(3, '"full_name": msg.full_name, "email": msg.email,')
L(3, '"subject": msg.subject, "message": msg.content,')
L(3, '"created_at": msg.created_at.isoformat(),')
L(2, '}, status=201)')
L(1, 'except Exception as e:')
L(2, 'return JsonResponse({"error": str(e)}, status=500)')
L('')

# ===== AI CHAT =====
L('@csrf_exempt')
L('@require_http_methods(["POST"])')
L('def ai_chat(request):')
L(1, 'try:')
L(2, 'data = json.loads(request.body)')
L(2, 'question = data.get("question", "").strip()')
L(2, 'if not question:')
L(3, 'return JsonResponse({"error": "Question is required."}, status=400)')
L(2, 'api_key = os.getenv("GOOGLE_GENERATIVE_API_KEY")')
L(2, 'if api_key:')
L(3, 'try:')
L(4, 'prompt = f"You are a helpful hostel assistant for EHostelFinder. Question: {question}"')
L(4, 'payload = json.dumps({"contents": [{"parts": [{"text": prompt}]}]}).encode("utf-8")')
L(4, 'url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={api_key}"')
L(4, 'req = urllib.request.Request(url, data=payload, headers={"Content-Type": "application/json"}, method="POST")')
L(4, 'with urllib.request.urlopen(req, timeout=30) as resp:')
L(5, 'return JsonResponse(json.loads(resp.read().decode("utf-8")))')
L(3, 'except Exception:')
L(4, 'pass')
L(2, 'ai_response = get_local_ai_response(question)')
L(2, 'return JsonResponse({"candidates": [{"content": {"parts": [{"text": ai_response}]}}]})')
L(1, 'except Exception as e:')
L(2, 'return JsonResponse({"error": str(e)}, status=500)')
L('')
L('@require_http_methods(["GET"])')
L('def get_messages_by_hostel(request, hostel_id):')
L(1, 'try:')
L(2, 'msgs = Message.objects.filter(hostel_id=hostel_id)')
L(2, 'return JsonResponse([{')
L(3, '"id": str(m.id), "hostel_id": str(m.hostel_id),')
L(3, '"full_name": m.full_name, "email": m.email,')
L(3, '"subject": m.subject, "message": m.content,')
L(3, '"created_at": m.created_at.isoformat(),')
L(2, '} for m in msgs], safe=False)')
L(1, 'except Exception as e:')
L(2, 'return JsonResponse({"error": str(e)}, status=500)')
L('')

# ===== UNIVERSITIES & CONTACT =====
L('@require_http_methods(["GET"])')
L('def universities(request):')
L(1, 'university_options = get_university_options()')
L(1, 'universities_data = []')
L(1, 'for uni in university_options:')
L(2, 'name = uni["name"]')
L(2, 'count = Hostel.objects.filter(university=name).count()')
L(2, 'top = Hostel.objects.filter(university=name).order_by("-rating").first()')
L(2, 'universities_data.append({')
L(3, '"name": name, "count": count,')
L(3, '"top_hostel": top.name if top else "",')
L(3, '"rating": float(top.rating) if top and top.rating else 0,')
L(2, '})')
L(1, 'universities_data.sort(key=lambda x: x["name"])')
L(1, 'return render(request, "universities.html", {"universities": universities_data})')
L('')
L('@csrf_exempt')
L('def contact(request):')
L(1, 'if request.method == "POST":')
L(2, 'try:')
L(3, 'ContactMessage.objects.create(')
L(4, 'full_name=request.POST.get("name", ""),')
L(4, 'email=request.POST.get("email", ""),')
L(4, 'subject=request.POST.get("subject", ""),')
L(4, 'message=request.POST.get("message", ""),')
L(3, ')')
L(3, 'return JsonResponse({"success": True, "message": "Message sent successfully!"})')
L(2, 'except Exception as e:')
L(3, 'return JsonResponse({"error": str(e)}, status=400)')
L(1, 'return render(request, "contact.html")')
L('')

# ===== GOOGLE AUTH =====
L('def google_auth(request):')
L(1, 'import urllib.parse')
L(1, 'from django.conf import settings')
L(1, 'redirect_uri = request.build_absolute_uri("/api/auth/google/callback/")')
L(1, 'params = {')
L(2, '"client_id": settings.GOOGLE_CLIENT_ID,')
L(2, '"redirect_uri": redirect_uri,')
L(2, '"response_type": "code",')
L(2, '"scope": "email profile",')
L(2, '"access_type": "online",')
L(1, '}')
L(1, 'url = f"https://accounts.google.com/o/oauth2/auth?{urllib.parse.urlencode(params)}"')
L(1, 'return redirect(url)')
L('')
L('def google_auth_callback(request):')
L(1, 'import urllib.parse, urllib.request')
L(1, 'from django.conf import settings')
L(1, 'from django.contrib.auth import login as auth_login')
L(1, 'code = request.GET.get("code")')
L(1, 'if not code:')
L(2, 'messages.error(request, "Google auth failed")')
L(2, 'return redirect("login")')
L(1, 'redirect_uri = request.build_absolute_uri("/api/auth/google/callback/")')
L(1, 'token_data = urllib.parse.urlencode({')
L(2, '"code": code,')
L(2, '"client_id": settings.GOOGLE_CLIENT_ID,')
L(2, '"client_secret": settings.GOOGLE_CLIENT_SECRET,')
L(2, '"redirect_uri": redirect_uri,')
L(2, '"grant_type": "authorization_code",')
L(1, '}).encode()')
L(1, 'try:')
L(2, 'req = urllib.request.Request("https://oauth2.googleapis.com/token", data=token_data, method="POST")')
L(2, 'req.add_header("Content-Type", "application/x-www-form-urlencoded")')
L(2, 'with urllib.request.urlopen(req, timeout=10) as resp:')
L(3, 'token_result = json.loads(resp.read().decode())')
L(2, 'access_token = token_result.get("access_token")')
L(2, 'user_req = urllib.request.Request(f"https://www.googleapis.com/oauth2/v2/userinfo?access_token={access_token}")')
L(2, 'with urllib.request.urlopen(user_req, timeout=10) as resp:')
L(3, 'user_info = json.loads(resp.read().decode())')
L(2, 'email = user_info.get("email")')
L(2, 'first_name = user_info.get("given_name", "")')
L(2, 'last_name = user_info.get("family_name", "")')
L(2, 'try:')
L(3, 'user = User.objects.get(email=email)')
L(2, 'except User.DoesNotExist:')
L(3, 'user = User.objects.create(')
L(4, 'id=str(uuid.uuid4()), email=email,')
L(4, 'first_name=first_name or email.split("@")[0],')
L(4, 'last_name=last_name, provider="google",')
L(3, ')')
L(2, 'auth_login(request, user)')
L(2, 'return redirect("home")')
L(1, 'except Exception as e:')
L(2, 'messages.error(request, "Google authentication failed")')
L(2, 'return redirect("login")')
L('')

# ===== MANAGER DASHBOARD =====
L('def manager_dashboard(request):')
L(1, 'if not request.user.is_authenticated:')
L(2, 'return redirect("login")')
L(1, 'profile = getattr(request.user, "profile", None)')
L(1, 'if not profile or profile.role != "manager":')
L(2, 'messages.error(request, "Access denied.")')
L(2, 'return redirect("home")')
L(1, 'hostel = profile.hostel')
L(1, 'if not hostel:')
L(2, 'messages.error(request, "No hostel assigned.")')
L(2, 'return redirect("home")')
L(1, 'return render(request, "manager/dashboard.html", {"hostel": hostel})')
L('')
L('@login_required')
L('def admin_manager_assign(request):')
L(1, 'profile = getattr(request.user, "profile", None)')
L(1, 'if not profile or profile.role != "admin":')
L(2, 'messages.error(request, "Access denied.")')
L(2, 'return redirect("home")')
L(1, 'return render(request, "admin/manager_assign.html")')
L('')

# ===== HOSTEL UPLOAD =====
L('@login_required')
L('@require_http_methods(["GET", "POST"])')
L('def hostel_upload(request):')
L(1, 'profile = getattr(request.user, "profile", None)')
L(1, 'if not profile or profile.role != "admin":')
L(2, 'messages.error(request, "Access denied.")')
L(2, 'return redirect("home")')
L(1, 'if request.method == "POST":')
L(2, 'form = HostelUploadForm(request.POST)')
L(2, 'if form.is_valid():')
L(3, 'hostel = Hostel.objects.create(')
L(4, 'name=form.cleaned_data["name"],')
L(4, 'description=form.cleaned_data["description"] or "",')
L(4, 'address=form.cleaned_data["address"],')
L(4, 'city=form.cleaned_data["city"],')
L(4, 'country=form.cleaned_data.get("country") or "Uganda",')
L(4, 'university=form.cleaned_data["university"] or "",')
L(4, 'distance="Near campus",')
L(4, 'price=form.cleaned_data["price_single"] or 0,')
L(4, 'rating=form.cleaned_data["rating"] or 0,')
L(4, 'amenities=[item.strip() for item in form.cleaned_data["amenities"].split(",") if item.strip()],')
L(4, 'image_url=form.cleaned_data["image_url"] or "",')
L(3, ')')
L(3, 'room_types = [')
L(4, '("Single", form.cleaned_data["price_single"], request.POST.get("room_available_single")),')
L(4, '("Double", form.cleaned_data["price_double"], request.POST.get("room_available_double")),')
L(4, '("Triple", form.cleaned_data["price_triple"], request.POST.get("room_available_triple")),')
L(4, '("Quadruple", form.cleaned_data["price_quadruple"], request.POST.get("room_available_quadruple")),')
L(3, ']')
L(3, 'for index, (room_type, price, is_avail) in enumerate(room_types, start=1):')
L(4, 'if price is None or price == 0:')
L(5, 'continue')
L(4, 'capacity = 1 if room_type == "Single" else 2 if room_type == "Double" else 3 if room_type == "Triple" else 4')
L(4, 'Room.objects.create(')
L(5, 'hostel=hostel, room_number=str(index),')
L(5, 'room_name=f"{room_type} Room",')
L(5, 'room_type=room_type, capacity=capacity,')
L(5, 'available_quantity=1, price_per_night=price,')
L(5, 'is_available=is_avail == "on",')
L(4, ')')
L(3, 'messages.success(request, "Hostel created successfully.")')
L(3, 'return redirect("hostel_upload")')
L(1, 'else:')
L(2, 'form = HostelUploadForm()')
L(1, 'return render(request, "admin/hostel_upload.html", {"form": form})')
L('')

# ===== MANAGER BOOKINGS =====
L('@require_http_methods(["GET"])')
L('def manager_bookings(request):')
L(1, 'if not request.user.is_authenticated:')
L(2, 'return JsonResponse({"error": "Auth required"}, status=401)')
L(1, 'profile = getattr(request.user, "profile", None)')
L(1, 'if not profile or profile.role != "manager":')
L(2, 'return JsonResponse({"error": "Access denied"}, status=403)')
L(1, 'hostel = profile.hostel')
L(1, 'if not hostel:')
L(2, 'return JsonResponse({"error": "No hostel assigned"}, status=400)')
L(1, 'bookings = Booking.objects.filter(hostel=hostel).select_related("customer", "room").order_by("-booked_at")')
L(1, 'return JsonResponse([{')
L(2, '"id": str(b.id), "booking_reference": b.booking_reference,')
L(2, '"customer_name": b.customer.get_full_name() or b.customer.email,')
L(2, '"customer_email": b.customer.email,')
L(2, '"room_number": b.room.room_number, "room_name": b.room.room_name,')
L(2, '"check_in": b.check_in.isoformat(), "check_out": b.check_out.isoformat(),')
L(2, '"guests": b.guests, "nights": b.nights,')
L(2, '"total_price": str(b.total_price),')
L(2, '"booking_status": b.booking_status, "payment_status": b.payment_status,')
L(2, '"special_requests": b.special_requests or "",')
L(1, '} for b in bookings], safe=False)')
L('')
L('@require_http_methods(["POST"])')
L('def manager_update_booking(request, booking_id):')
L(1, 'if not request.user.is_authenticated:')
L(2, 'return JsonResponse({"error": "Auth required"}, status=401)')
L(1, 'profile = getattr(request.user, "profile", None)')
L(1, 'if not profile or profile.role != "manager":')
L(2, 'return JsonResponse({"error": "Access denied"}, status=403)')
L(1, 'hostel = profile.hostel')
L(1, 'if not hostel:')
L(2, 'return JsonResponse({"error": "No hostel assigned"}, status=400)')
L(1, 'try:')
L(2, 'data = json.loads(request.body)')
L(2, 'booking = get_object_or_404(Booking, id=booking_id, hostel=hostel)')
L(2, 'status = data.get("booking_status")')
L(2, 'if status and status in dict(BookingStatus.choices).keys():')
L(3, 'booking.booking_status = status')
L(3, 'booking.save(update_fields=["booking_status"])')
L(2, 'return JsonResponse({"success": True})')
L(1, 'except Exception as e:')
L(2, 'return JsonResponse({"error": str(e)}, status=400)')
L('')

# ===== MANAGER CHECKINS =====
L('@require_http_methods(["GET", "POST"])')
L('def manager_checkins(request):')
L(1, 'if not request.user.is_authenticated:')
L(2, 'return JsonResponse({"error": "Auth required"}, status=401)')
L(1, 'profile = getattr(request.user, "profile", None)')
L(1, 'if not profile or profile.role != "manager":')
L(2, 'return JsonResponse({"error": "Access denied"}, status=403)')
L(1, 'hostel = profile.hostel')
L(1, 'if not hostel:')
L(2, 'return JsonResponse({"error": "No hostel assigned"}, status=400)')
L(1, 'if request.method == "GET":')
L(2, 'bookings = Booking.objects.filter(hostel=hostel, booking_status="Checked In").select_related("customer", "room")')
L(2, 'return JsonResponse([{')
L(3, '"id": str(b.id), "booking_reference": b.booking_reference,')
L(3, '"customer_name": b.customer.get_full_name() or b.customer.email,')
L(3, '"customer_email": b.customer.email,')
L(3, '"room_number": b.room.room_number, "room_name": b.room.room_name,')
L(3, '"check_in": b.check_in.isoformat(), "check_out": b.check_out.isoformat(),')
L(3, '"guests": b.guests, "total_price": str(b.total_price),')
L(2, '} for b in bookings], safe=False)')
L('')

# ===== MANAGER ROOMS =====
L('@require_http_methods(["GET", "POST"])')
L('def manager_rooms(request):')
L(1, 'if not request.user.is_authenticated:')
L(2, 'return JsonResponse({"error": "Auth required"}, status=401)')
L(1, 'profile = getattr(request.user, "profile", None)')
L(1, 'if not profile or profile.role != "manager":')
L(2, 'return JsonResponse({"error": "Access denied"}, status=403)')
L(1, 'hostel = profile.hostel')
L(1, 'if not hostel:')
L(2, 'return JsonResponse({"error": "No hostel assigned"}, status=400)')
L(1, 'if request.method == "GET":')
L(2, 'rooms = Room.objects.filter(hostel=hostel)')
L(2, 'return JsonResponse([{')
L(3, '"id": str(r.id), "room_number": r.room_number,')
L(3, '"room_name": r.room_name, "room_type": r.room_type,')
L(3, '"capacity": r.capacity, "available_quantity": r.available_quantity,')
L(3, '"price_per_night": str(r.price_per_night),')
L(3, '"status": r.status, "is_available": r.is_available,')
L(2, '} for r in rooms], safe=False)')
L(1, 'try:')
L(2, 'data = json.loads(request.body)')
L(2, 'room_id = data.get("room_id")')
L(2, 'room = get_object_or_404(Room, id=room_id, hostel=hostel)')
L(2, 'status = data.get("status")')
L(2, 'if status and status in dict(RoomStatus.choices).keys():')
L(3, 'room.status = status')
L(3, 'room.is_available = status == "Available"')
L(2, 'if data.get("is_available") is not None:')
L(3, 'room.is_available = data.get("is_available") in [True, "true"]')
L(2, 'if data.get("available_quantity") is not None:')
L(3, 'room.available_quantity = int(data.get("available_quantity"))')
L(2, 'room.save()')
L(2, 'return JsonResponse({"success": True})')
L(1, 'except Exception as e:')
L(2, 'return JsonResponse({"error": str(e)}, status=400)')
L('')

# ===== ADMIN MANAGER MANAGEMENT =====
L('@csrf_exempt')
L('@require_http_methods(["POST"])')
L('def admin_assign_manager(request):')
L(1, 'if not request.user.is_authenticated:')
L(2, 'return JsonResponse({"error": "Auth required"}, status=401)')
L(1, 'profile = getattr(request.user, "profile", None)')
L(1, 'if not profile or profile.role != "admin":')
L(2, 'return JsonResponse({"error": "Access denied"}, status=403)')
L(1, 'try:')
L(2, 'data = json.loads(request.body)')
L(2, 'manager_id, hostel_id = data.get("manager_id"), data.get("hostel_id")')
L(2, 'if not manager_id or not hostel_id:')
L(3, 'return JsonResponse({"error": "manager_id and hostel_id required"}, status=400)')
L(2, 'manager_profile = get_object_or_404(Profile, id=manager_id, role="manager")')
L(2, 'hostel = get_object_or_404(Hostel, id=hostel_id)')
L(2, 'manager_profile.hostel = hostel')
L(2, 'manager_profile.save()')
L(2, 'return JsonResponse({"success": True, "message": f"Manager {manager_profile.full_name} assigned to {hostel.name}"})')
L(1, 'except Exception as e:')
L(2, 'return JsonResponse({"error": str(e)}, status=400)')
L('')
L('@require_http_methods(["POST"])')
L('def admin_remove_manager(request):')
L(1, 'if not request.user.is_authenticated:')
L(2, 'return JsonResponse({"error": "Auth required"}, status=401)')
L(1, 'profile = getattr(request.user, "profile", None)')
L(1, 'if not profile or profile.role != "admin":')
L(2, 'return JsonResponse({"error": "Access denied"}, status=403)')
L(1, 'try:')
L(2, 'data = json.loads(request.body)')
L(2, 'manager_id = data.get("manager_id")')
L(2, 'if not manager_id:')
L(3, 'return JsonResponse({"error": "manager_id required"}, status=400)')
L(2, 'manager_profile = get_object_or_404(Profile, id=manager_id, role="manager")')
L(2, 'manager_profile.hostel = None')
L(2, 'manager_profile.save()')
L(2, 'return JsonResponse({"success": True})')
L(1, 'except Exception as e:')
L(2, 'return JsonResponse({"error": str(e)}, status=400)')
L('')
L('@require_http_methods(["GET"])')
L('def api_managers(request):')
L(1, 'if not request.user.is_authenticated:')
L(2, 'return JsonResponse({"error": "Auth required"}, status=401)')
L(1, 'profile = getattr(request.user, "profile", None)')
L(1, 'if not profile or profile.role != "admin":')
L(2, 'return JsonResponse({"error": "Access denied"}, status=403)')
L(1, 'managers = Profile.objects.filter(role="manager").select_related("hostel")')
L(1, 'return JsonResponse([{')
L(2, '"id": str(m.id), "full_name": m.full_name, "email": m.email,')
L(2, '"hostel_id": str(m.hostel_id) if m.hostel else None,')
L(2, '"hostel_name": m.hostel.name if m.hostel else None,')
L(1, '} for m in managers], safe=False)')
L('')
L('@csrf_exempt')
L('@require_http_methods(["POST"])')
L('def admin_create_manager(request):')
L(1, 'if not request.user.is_authenticated:')
L(2, 'return JsonResponse({"error": "Auth required"}, status=401)')
L(1, 'profile = getattr(request.user, "profile", None)')
L(1, 'if not profile or profile.role != "admin":')
L(2, 'return JsonResponse({"error": "Access denied"}, status=403)')
L(1, 'try:')
L(2, 'data = json.loads(request.body)')
L(2, 'full_name = data.get("full_name", "").strip()')
L(2, 'email = data.get("email", "").strip()')
L(2, 'phone = data.get("phone", "").strip()')
L(2, 'password = data.get("password", "")')
L(2, 'if not full_name or not email or not password:')
L(3, 'return JsonResponse({"error": "Full name, email, and password required"}, status=400)')
L(2, 'if len(password) < 8:')
L(3, 'return JsonResponse({"error": "Password must be at least 8 characters"}, status=400)')
L(2, 'if User.objects.filter(email=email).exists():')
L(3, 'return JsonResponse({"error": "Email already exists"}, status=400)')
L(2, 'name_parts = full_name.split(" ", 1)')
L(2, 'first_name = name_parts[0] if name_parts else full_name')
L(2, 'last_name = name_parts[1] if len(name_parts) > 1 else ""')
L(2, 'user = User.objects.create(')
L(3, 'id=str(uuid.uuid4()), email=email,')
L(3, 'first_name=first_name, last_name=last_name,')
L(3, 'is_email_verified=True,')
L(2, ')')
L(2, 'user.set_password(password)')
L(2, 'user.save()')
L(2, 'Profile.objects.create(')
L(3, 'user=user, full_name=full_name,')
L(3, 'email=email, phone=phone or None, role="manager",')
L(2, ')')
L(2, 'return JsonResponse({"success": True, "message": f"Manager {full_name} created successfully"})')
L(1, 'except Exception as e:')
L(2, 'return JsonResponse({"error": str(e)}, status=400)')
L('')
L('@require_http_methods(["GET"])')
L('def api_unassigned_managers(request):')
L(1, 'if not request.user.is_authenticated:')
L(2, 'return JsonResponse({"error": "Auth required"}, status=401)')
L(1, 'profile = getattr(request.user, "profile", None)')
L(1, 'if not profile or profile.role != "admin":')
L(2, 'return JsonResponse({"error": "Access denied"}, status=403)')
L(1, 'managers = Profile.objects.filter(role="manager", hostel__isnull=True)')
L(1, 'return JsonResponse([{"id": str(m.id), "full_name": m.full_name, "email": m.email} for m in managers], safe=False)')
L('')
L('@require_http_methods(["GET"])')
L('def api_hostel_managers(request, hostel_id):')
L(1, 'if not request.user.is_authenticated:')
L(2, 'return JsonResponse({"error": "Auth required"}, status=401)')
L(1, 'profile = getattr(request.user, "profile", None)')
L(1, 'if not profile or profile.role != "admin":')
L(2, 'return JsonResponse({"error": "Access denied"}, status=403)')
L(1, 'hostel = get_object_or_404(Hostel, id=hostel_id)')
L(1, 'managers = Profile.objects.filter(role="manager", hostel=hostel)')
L(1, 'return JsonResponse([{"id": str(m.id), "full_name": m.full_name, "email": m.email} for m in managers], safe=False)')
L('')
L('@require_http_methods(["POST"])')
L('def manager_checkout(request, booking_id):')
L(1, 'if not request.user.is_authenticated:')
L(2, 'return JsonResponse({"error": "Auth required"}, status=401)')
L(1, 'profile = getattr(request.user, "profile", None)')
L(1, 'if not profile or profile.role != "manager":')
L(2, 'return JsonResponse({"error": "Access denied"}, status=403)')
L(1, 'hostel = profile.hostel')
L(1, 'if not hostel:')
L(2, 'return JsonResponse({"error": "No hostel assigned"}, status=400)')
L(1, 'try:')
L(2, 'booking = get_object_or_404(Booking, id=booking_id, hostel=hostel)')
L(2, 'booking.booking_status = "Checked Out"')
L(2, 'booking.save()')
L(2, 'return JsonResponse({"success": True})')
L(1, 'except Exception as e:')
L(2, 'return JsonResponse({"error": str(e)}, status=400)')
L('')

# ===== PASSWORD RESET =====
L('@require_http_methods(["GET", "POST"])')
L('def forgot_password(request):')
L(1, 'if request.method == "POST":')
L(2, 'form = ForgotPasswordForm(request.POST)')
L(2, 'if form.is_valid():')
L(3, 'email = form.cleaned_data["email"]')
L(3, 'try:')
L(4, 'user = User.objects.get(email=email)')
L(4, 'from .email_utils import send_password_reset_email')
L(4, 'send_password_reset_email(user, request)')
L(3, 'except User.DoesNotExist:')
L(4, 'pass')
L(3, 'messages.success(request, "If an account with that email exists, a reset link has been sent.")')
L(3, 'return redirect("login")')
L(1, 'else:')
L(2, 'form = ForgotPasswordForm()')
L(1, 'return render(request, "forgot_password.html", {"form": form})')
L('')
L('@require_http_methods(["GET", "POST"])')
L('def reset_password(request, token):')
L(1, 'from .models import PasswordResetToken')
L(1, 'try:')
L(2, 'reset_token = PasswordResetToken.objects.select_related("user").get(token=token)')
L(1, 'except PasswordResetToken.DoesNotExist:')
L(2, 'return render(request, "password_reset_status.html", {"status": "invalid", "message": "Invalid reset link."})')
L(1, 'if reset_token.is_expired:')
L(2, 'return render(request, "password_reset_status.html", {"status": "expired", "message": "This reset link has expired."})')
L(1, 'if reset_token.is_used:')
L(2, 'return render(request, "password_reset_status.html", {"status": "used", "message": "This link has already been used."})')
L(1, 'if request.method == "POST":')
L(2, 'form = ResetPasswordForm(request.POST)')
L(2, 'if form.is_valid():')
L(3, 'user = reset_token.user')
L(3, 'user.set_password(form.cleaned_data["new_password"])')
L(3, 'user.save()')
L(3, 'reset_token.used_at = timezone.now()')
L(3, 'reset_token.save()')
L(3, 'messages.success(request, "Your password has been reset.")')
L(3, 'return redirect("login")')
L(1, 'else:')
L(2, 'form = ResetPasswordForm()')
L(1, 'return render(request, "reset_password.html", {"form": form, "token": token})')
L('')

# ===== PROFILE =====
L('@login_required')
L('def profile(request):')
L(1, 'user = request.user')
L(1, 'profile_obj = getattr(user, "profile", None)')
L(1, 'if request.method == "POST":')
L(2, 'form = ProfileUpdateForm(request.POST, instance=profile_obj)')
L(2, 'if form.is_valid():')
L(3, 'form.save()')
L(3, 'user.first_name = request.POST.get("first_name", user.first_name)')
L(3, 'user.last_name = request.POST.get("last_name", user.last_name)')
L(3, 'user.save(update_fields=["first_name", "last_name"])')
L(3, 'messages.success(request, "Profile updated successfully")')
L(3, 'return redirect("profile")')
L(1, 'else:')
L(2, 'form = ProfileUpdateForm(instance=profile_obj)')
L(1, 'return render(request, "profile.html", {"form": form, "profile": profile_obj})')
L('')
L('@login_required')
L('def my_bookings(request):')
L(1, 'bookings = Booking.objects.filter(customer=request.user).select_related("hostel", "room").order_by("-booked_at")')
L(1, 'return render(request, "my_bookings.html", {"bookings": bookings})')
L('')

# ===== FAVORITES =====
L('@login_required')
L('@require_http_methods(["POST"])')
L('def toggle_favorite(request):')
L(1, 'try:')
L(2, 'data = json.loads(request.body)')
L(2, 'hostel = get_object_or_404(Hostel, id=data.get("hostel_id"))')
L(2, 'fav, created = Favorite.objects.get_or_create(customer=request.user, hostel=hostel)')
L(2, 'if not created:')
L(3, 'fav.delete()')
L(3, 'return JsonResponse({"favorited": False})')
L(2, 'return JsonResponse({"favorited": True})')
L(1, 'except Exception as e:')
L(2, 'return JsonResponse({"error": str(e)}, status=400)')
L('')
L('@login_required')
L('def my_favorites(request):')
L(1, 'favorites = Favorite.objects.filter(customer=request.user).select_related("hostel")')
L(1, 'return render(request, "my_favorites.html", {"favorites": favorites})')
L('')

# ===== BOOKING CANCELLATION =====
L('@login_required')
L('@require_http_methods(["POST"])')
L('def cancel_booking(request, booking_id):')
L(1, 'try:')
L(2, 'booking = get_object_or_404(Booking, id=booking_id, customer=request.user)')
L(2, 'if booking.booking_status in ["Checked In", "Checked Out"]:')
L(3, 'return JsonResponse({"error": "Cannot cancel an active or completed booking"}, status=400)')
L(2, 'if booking.booking_status == "Cancelled":')
L(3, 'return JsonResponse({"error": "Booking is already cancelled"}, status=400)')
L(2, 'booking.booking_status = "Cancelled"')
L(2, 'booking.payment_status = "Refunded"')
L(2, 'booking.save(update_fields=["booking_status", "payment_status"])')
L(2, 'Notification.objects.create(')
L(3, 'user=request.user, title="Booking Cancelled",')
L(3, 'message=f"Booking {booking.booking_reference} cancelled.")')
L(2, 'return JsonResponse({"success": True, "message": "Booking cancelled successfully"})')
L(1, 'except Exception as e:')
L(2, 'return JsonResponse({"error": str(e)}, status=400)')
L('')

# ===== NOTIFICATIONS =====
L('@login_required')
L('def view_notifications(request):')
L(1, 'notifications = Notification.objects.filter(user=request.user).order_by("-created_at")')
L(1, 'unread_count = notifications.filter(is_read=False).count()')
L(1, 'return render(request, "notifications.html", {"notifications": notifications, "unread_count": unread_count})')
L('')

# ===== WRITE FILE =====
with open('hostels/views.py', 'a', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f"Appended {len(lines)} lines to hostels/views.py")
</｜｜DSML｜｜parameter>
</create_file>
