#!/usr/bin/env python3
"""Append remaining view functions to hostels/views.py"""
import os, ast, re, sys

os.chdir(r'c:\Users\user\ehostelfinder')

with open('hostels/views.py', 'r', encoding='utf-8') as f:
    existing = f.read()

lines = existing.rstrip().split('\n')
if lines and lines[-1] == '':
    lines.pop()

# Ensure no trailing blank line to start
indent = 0
def w(s):
    if indent:
        lines.append('    ' * indent + s)
    else:
        lines.append(s)
def i(n=1):
    global indent; indent += n
def d(n=1):
    global indent; indent -= n

# ===== ADDITIONAL VIEWS =====

w('')
w('@csrf_exempt')
w('@require_http_methods(["POST"])')
w('def ai_chat(request):')
i()
w('try:')
i()
w('data = json.loads(request.body.decode("utf-8") if isinstance(request.body, bytes) else request.body)')
w('question = data.get("question", "").strip()')
w("if not question:")
i()
w('return JsonResponse({"error": "Question is required."}, status=400)')
d()
w("api_key = os.getenv('GOOGLE_GENERATIVE_API_KEY')")
w('if api_key:')
i()
w('try:')
i()
w('prompt = "You are a helpful hostel assistant for EHostelFinder. Answer questions about hostel services, bookings, and amenities. Be friendly, concise, and helpful. "')
w("prompt += f'Question: {question}'")
w("payload = json.dumps({'contents': [{'parts': [{'text': prompt}]}]}).encode('utf-8')")
w("url = f'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={api_key}'")
w("req = urllib.request.Request(url, data=payload, headers={'Content-Type': 'application/json'}, method='POST')")
w('with urllib.request.urlopen(req, timeout=30) as resp:')
i()
w('result = json.loads(resp.read().decode("utf-8"))')
d()
w('return JsonResponse(result)')
d()
w('except: pass')
d()
w('from .local_ai import get_local_ai_response')
w('ai_response = get_local_ai_response(question)')
w('return JsonResponse({"candidates": [{"content": {"parts": [{"text": ai_response}]}}]})')
d()
w('except Exception:')
i()
w('from .local_ai import get_local_ai_response')
w('ai_response = get_local_ai_response(question)')
w('return JsonResponse({"candidates": [{"content": {"parts": [{"text": ai_response}]}}]})')
d()
d()

w('')
w('@require_http_methods(["GET"])')
w('def get_booking_by_id(request, id):')
i()
w('try:')
i()
w('booking = get_object_or_404(Booking, id=id)')
w('if request.user.id == booking.customer_id:')
i()
w('return JsonResponse({"id": str(booking.id), "booking_reference": booking.booking_reference, "hostel_id": str(booking.hostel_id), "room_id": str(booking.room_id), "check_in": booking.check_in.isoformat(), "check_out": booking.check_out.isoformat(), "guests": booking.guests, "nights": booking.nights, "total_price": str(booking.total_price), "booking_status": booking.booking_status, "payment_status": booking.payment_status})')
d()
w('return JsonResponse({"error": "Not authorized"}, status=403)')
d()
w('except Exception as e:')
i()
w('return JsonResponse({"error": str(e)}, status=500)')
d()
d()

w('')
w('@csrf_exempt')
w('@require_http_methods(["POST"])')
w('def create_message(request):')
i()
w('try:')
i()
w('data = json.loads(request.body)')
w('hostel = get_object_or_404(Hostel, id=data.get("hostelId"))')
w('message = Message.objects.create(hostel=hostel, user=request.user if request.user.is_authenticated else None, full_name=data.get("fullName", ""), email=data.get("email", ""), phone=data.get("phone", ""), subject=data.get("subject", ""), content=data.get("content", "") or data.get("message", ""))')
w('return JsonResponse({"id": str(message.id), "created_at": message.created_at.isoformat()}, status=201)')
d()
w('except Exception as e:')
i()
w('return JsonResponse({"error": str(e)}, status=500)')
d()
d()

w('')
w('@require_http_methods(["GET"])')
w('def get_messages_by_hostel(request, hostel_id):')
i()
w('try:')
i()
w('msgs = Message.objects.filter(hostel_id=hostel_id)')
w('return JsonResponse([{"id": str(m.id), "full_name": m.full_name, "email": m.email, "phone": m.phone, "subject": m.subject, "message": m.content, "created_at": m.created_at.isoformat()} for m in msgs], safe=False)')
d()
w('except Exception as e:')
i()
w('return JsonResponse({"error": str(e)}, status=500)')
d()
d()

w('')
w('def universities(request):')
i()
w('university_options = get_university_options()')
w('universities_data = []')
w('for uni in university_options:')
i()
w('name = uni["name"]')
w('count = Hostel.objects.filter(university=name).count()')
w('top = Hostel.objects.filter(university=name).order_by("-rating").first()')
w('universities_data.append({"name": name, "count": count, "top_hostel": top.name if top else "", "rating": float(top.rating) if top and top.rating else 0})')
d()
w('universities_data.sort(key=lambda x: x["name"])')
w('return render(request, "universities.html", {"universities": universities_data})')
d()

w('')
w('@csrf_exempt')
w('def contact(request):')
i()
w('if request.method == "POST":')
i()
w('try:')
i()
w('ContactMessage.objects.create(full_name=request.POST.get("name", ""), email=request.POST.get("email", ""), subject=request.POST.get("subject", ""), message=request.POST.get("message", ""))')
w('return JsonResponse({"success": True, "message": "Message sent successfully!"})')
d()
w('except Exception as e:')
i()
w('return JsonResponse({"error": str(e)}, status=400)')
d()
d()
w('return render(request, "contact.html")')
d()

w('')
w('def google_auth(request):')
i()
w('import urllib.parse')
w('from django.conf import settings')
w('redirect_uri = request.build_absolute_uri("/api/auth/google/callback/")')
w('params = {"client_id": settings.GOOGLE_CLIENT_ID, "redirect_uri": redirect_uri, "response_type": "code", "scope": "email profile", "access_type": "online"}')
w('auth_url = f"https://accounts.google.com/o/oauth2/auth?{urllib.parse.urlencode(params)}"')
w('return redirect(auth_url)')
d()

w('')
w('def google_auth_callback(request):')
i()
w('import urllib.parse')
w('from django.conf import settings')
w('from django.contrib.auth import login as auth_login')
w('code = request.GET.get("code")')
w('if not code:')
i()
w('messages.error(request, "Google auth failed")')
w('return redirect("login")')
d()
w('redirect_uri = request.build_absolute_uri("/api/auth/google/callback/")')
w('try:')
i()
w('token_data = urllib.parse.urlencode({"code": code, "client_id": settings.GOOGLE_CLIENT_ID, "client_secret": settings.GOOGLE_CLIENT_SECRET, "redirect_uri": redirect_uri, "grant_type": "authorization_code"}).encode()')
w('req = urllib.request.Request("https://oauth2.googleapis.com/token", data=token_data, method="POST")')
w('req.add_header("Content-Type", "application/x-www-form-urlencoded")')
w('with urllib.request.urlopen(req, timeout=10) as resp:')
i()
w('token_result = json.loads(resp.read().decode())')
d()
w('access_token = token_result.get("access_token")')
w('user_req = urllib.request.Request(f"https://www.googleapis.com/oauth2/v2/userinfo?access_token={access_token}")')
w('with urllib.request.urlopen(user_req, timeout=10) as resp:')
i()
w('user_info = json.loads(resp.read().decode())')
d()
w('email = user_info.get("email")')
w('first_name = user_info.get("given_name", "")')
w('last_name = user_info.get("family_name", "")')
w('try:')
i()
w('user = User.objects.get(email=email)')
d()
w('except User.DoesNotExist:')
i()
w('user = User.objects.create(id=str(uuid.uuid4()), email=email, first_name=first_name or email.split("@")[0], last_name=last_name, provider="google")')
d()
w('auth_login(request, user)')
w('return redirect("home")')
d()
w('except Exception:')
i()
w('messages.error(request, "Google auth failed")')
w('return redirect("login")')
d()
d()

# ===== Manager Views =====
w('')
w('def manager_dashboard(request):')
i()
w('if not request.user.is_authenticated:')
i()
w('return redirect("login")')
d()
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "manager":')
i()
w('messages.error(request, "Access denied. Manager only.")')
w('return redirect("home")')
d()
w('hostel = profile.hostel')
w('if not hostel:')
i()
w('messages.error(request, "No hostel assigned.")')
w('return redirect("home")')
d()
w('return render(request, "manager/dashboard.html", {"hostel": hostel})')
d()

w('')
w('@login_required')
w('def admin_manager_assign(request):')
i()
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "admin":')
i()
w('messages.error(request, "Access denied. Admin only.")')
w('return redirect("home")')
d()
w('return render(request, "admin/manager_assign.html")')
d()

w('')
w('@login_required')
w('@require_http_methods(["GET", "POST"])')
w('def hostel_upload(request):')
i()
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "admin":')
i()
w('messages.error(request, "Access denied.")')
w('return redirect("home")')
d()
w('if request.method == "POST":')
i()
w('form = HostelUploadForm(request.POST)')
w('if form.is_valid():')
i()
w('hostel = Hostel.objects.create(name=form.cleaned_data["name"], description=form.cleaned_data.get("description",""), address=form.cleaned_data["address"], city=form.cleaned_data["city"], country=form.cleaned_data.get("country") or "Uganda", university=form.cleaned_data.get("university",""), distance="Near campus", price=form.cleaned_data.get("price_single") or 0, rating=form.cleaned_data.get("rating") or 0, amenities=[x.strip() for x in form.cleaned_data["amenities"].split(",") if x.strip()], image_url=form.cleaned_data.get("image_url",""))')
w('room_types = [("Single", form.cleaned_data["price_single"], request.POST.get("room_available_single")), ("Double", form.cleaned_data["price_double"], request.POST.get("room_available_double")), ("Triple", form.cleaned_data["price_triple"], request.POST.get("room_available_triple")), ("Quadruple", form.cleaned_data["price_quadruple"], request.POST.get("room_available_quadruple"))]')
w('for idx, (rt, pr, avail) in enumerate(room_types, 1):')
i()
w('if pr is None or pr == 0: continue')
w('cap = 1 if rt == "Single" else 2 if rt == "Double" else 3 if rt == "Triple" else 4')
w('Room.objects.create(hostel=hostel, room_number=str(idx), room_name=f"{rt} Room", room_type=rt, capacity=cap, available_quantity=1, price_per_night=pr, is_available=avail == "on")')
d()
w('messages.success(request, "Hostel created.")')
w('return redirect("hostel_upload")')
d()
d()
w('else:')
i()
w('form = HostelUploadForm()')
d()
w('return render(request, "admin/hostel_upload.html", {"form": form})')
d()

w('')
w('@require_http_methods(["GET"])')
w('def manager_bookings(request):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "manager": return JsonResponse({"error": "Access denied"}, status=403)')
w('hostel = profile.hostel')
w('if not hostel: return JsonResponse({"error": "No hostel"}, status=400)')
w('bookings = Booking.objects.filter(hostel=hostel).select_related("customer", "room").order_by("-booked_at")')
w('return JsonResponse([{"id": str(b.id), "booking_reference": b.booking_reference, "customer_name": b.customer.get_full_name() or b.customer.email, "customer_email": b.customer.email, "room_number": b.room.room_number, "room_name": b.room.room_name, "check_in": b.check_in.isoformat(), "check_out": b.check_out.isoformat(), "guests": b.guests, "nights": b.nights, "total_price": str(b.total_price), "booking_status": b.booking_status, "payment_status": b.payment_status, "special_requests": b.special_requests or ""} for b in bookings], safe=False)')
d()

w('')
w('@require_http_methods(["POST"])')
w('def manager_update_booking(request, booking_id):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "manager": return JsonResponse({"error": "Access denied"}, status=403)')
w('hostel = profile.hostel')
w('if not hostel: return JsonResponse({"error": "No hostel"}, status=400)')
w('try:')
i()
w('data = json.loads(request.body)')
w('booking = get_object_or_404(Booking, id=booking_id, hostel=hostel)')
w('status = data.get("booking_status")')
w('if status and status in dict(BookingStatus.choices).keys():')
i()
w('booking.booking_status = status')
w('booking.save(update_fields=["booking_status"])')
d()
w('return JsonResponse({"success": True, "message": "Booking updated"})')
d()
w('except Exception as e:')
i()
w('return JsonResponse({"error": str(e)}, status=400)')
d()
d()

w('')
w('@require_http_methods(["GET", "POST"])')
w('def manager_checkins(request):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "manager": return JsonResponse({"error": "Access denied"}, status=403)')
w('hostel = profile.hostel')
w('if not hostel: return JsonResponse({"error": "No hostel"}, status=400)')
w('if request.method == "GET":')
i()
w('bookings = Booking.objects.filter(hostel=hostel, booking_status="Checked In").select_related("customer", "room")')
w('return JsonResponse([{"id": str(b.id), "booking_reference": b.booking_reference, "customer_name": b.customer.get_full_name() or b.customer.email, "customer_email": b.customer.email, "room_number": b.room.room_number, "room_name": b.room.room_name, "check_in": b.check_in.isoformat(), "check_out": b.check_out.isoformat(), "guests": b.guests, "total_price": str(b.total_price)} for b in bookings], safe=False)')
d()
d()

w('')
w('@require_http_methods(["GET", "POST"])')
w('def manager_rooms(request):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "manager": return JsonResponse({"error": "Access denied"}, status=403)')
w('hostel = profile.hostel')
w('if not hostel: return JsonResponse({"error": "No hostel"}, status=400)')
w('if request.method == "GET":')
i()
w('rooms = Room.objects.filter(hostel=hostel)')
w('return JsonResponse([{"id": str(r.id), "room_number": r.room_number, "room_name": r.room_name, "room_type": r.room_type, "capacity": r.capacity, "available_quantity": r.available_quantity, "price_per_night": str(r.price_per_night), "status": r.status, "is_available": r.is_available} for r in rooms], safe=False)')
d()
w('try:')
i()
w('data = json.loads(request.body)')
w('room = get_object_or_404(Room, id=data.get("room_id"), hostel=hostel)')
w('if data.get("status") in dict(RoomStatus.choices).keys():')
i()
w('room.status = data["status"]')
w('room.is_available = data["status"] == "Available"')
d()
w('if data.get("is_available") is not None:')
i()
w('room.is_available = data["is_available"] == "true" or data["is_available"] is True')
d()
w('if data.get("available_quantity") is not None:')
i()
w('room.available_quantity = int(data["available_quantity"])')
d()
w('room.save()')
w('return JsonResponse({"success": True})')
d()
w('except Exception as e:')
i()
w('return JsonResponse({"error": str(e)}, status=400)')
d()
d()

w('')
w('@csrf_exempt')
w('@require_http_methods(["POST"])')
w('def admin_assign_manager(request):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "admin": return JsonResponse({"error": "Access denied"}, status=403)')
w('try:')
i()
w('data = json.loads(request.body)')
w('manager_id, hostel_id = data.get("manager_id"), data.get("hostel_id")')
w('if not manager_id or not hostel_id: return JsonResponse({"error": "manager_id and hostel_id required"}, status=400)')
w('manager_profile = get_object_or_404(Profile, id=manager_id, role="manager")')
w('hostel = get_object_or_404(Hostel, id=hostel_id)')
w('manager_profile.hostel = hostel; manager_profile.save()')
w('return JsonResponse({"success": True, "message": f"Manager {manager_profile.full_name} assigned to {hostel.name}"})')
d()
w('except Exception as e:')
i()
w('return JsonResponse({"error": str(e)}, status=400)')
d()
d()

w('')
w('@require_http_methods(["POST"])')
w('def admin_remove_manager(request):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "admin": return JsonResponse({"error": "Access denied"}, status=403)')
w('try:')
i()
w('data = json.loads(request.body)')
w('manager_id = data.get("manager_id")')
w('if not manager_id: return JsonResponse({"error": "manager_id required"}, status=400)')
w('manager_profile = get_object_or_404(Profile, id=manager_id, role="manager")')
w('manager_profile.hostel = None; manager_profile.save()')
w('return JsonResponse({"success": True})')
d()
w('except Exception as e:')
i()
w('return JsonResponse({"error": str(e)}, status=400)')
d()
d()

w('')
w('@require_http_methods(["GET"])')
w('def api_managers(request):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "admin": return JsonResponse({"error": "Access denied"}, status=403)')
w('managers = Profile.objects.filter(role="manager").select_related("hostel")')
w('return JsonResponse([{"id": str(m.id), "full_name": m.full_name, "email": m.email, "phone": m.phone, "hostel_id": str(m.hostel_id) if m.hostel else None, "hostel_name": m.hostel.name if m.hostel else None} for m in managers], safe=False)')
d()

w('')
w('@csrf_exempt')
w('@require_http_methods(["POST"])')
w('def admin_create_manager(request):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "admin": return JsonResponse({"error": "Access denied"}, status=403)')
w('try:')
i()
w('data = json.loads(request.body)')
w('full_name = data.get("full_name", "").strip()')
w('email = data.get("email", "").strip()')
w('phone = data.get("phone", "").strip()')
w('password = data.get("password", "")')
w('if not full_name or not email or not password: return JsonResponse({"error": "Full name, email, and password required"}, status=400)')
w('if len(password) < 8: return JsonResponse({"error": "Password must be at least 8 characters"}, status=400)')
w('if User.objects.filter(email=email).exists(): return JsonResponse({"error": "User already exists"}, status=400)')
w('name_parts = full_name.split(" ", 1)')
w('first_name = name_parts[0] if name_parts else full_name')
w('last_name = name_parts[1] if len(name_parts) > 1 else ""')
w('user = User.objects.create(id=str(uuid.uuid4()), email=email, first_name=first_name, last_name=last_name, is_email_verified=True)')
w('user.set_password(password); user.save()')
w('Profile.objects.create(user=user, full_name=full_name, email=email, phone=phone or None, role="manager")')
w('return JsonResponse({"success": True, "message": f"Manager {full_name} created"})')
d()
w('except Exception as e:')
i()
w('return JsonResponse({"error": str(e)}, status=400)')
d()
d()

w('')
w('@require_http_methods(["GET"])')
w('def api_unassigned_managers(request):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "admin": return JsonResponse({"error": "Access denied"}, status=403)')
w('managers = Profile.objects.filter(role="manager", hostel__isnull=True)')
w('return JsonResponse([{"id": str(m.id), "full_name": m.full_name, "email": m.email} for m in managers], safe=False)')
d()

w('')
w('@require_http_methods(["GET"])')
w('def api_hostel_managers(request, hostel_id):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "admin": return JsonResponse({"error": "Access denied"}, status=403)')
w('hostel = get_object_or_404(Hostel, id=hostel_id)')
w('managers = Profile.objects.filter(role="manager", hostel=hostel)')
w('return JsonResponse([{"id": str(m.id), "full_name": m.full_name, "email": m.email, "phone": m.phone} for m in managers], safe=False)')
d()

w('')
w('@require_http_methods(["POST"])')
w('def manager_checkout(request, booking_id):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "manager": return JsonResponse({"error": "Access denied"}, status=403)')
w('hostel = profile.hostel')
w('if not hostel: return JsonResponse({"error": "No hostel"}, status=400)')
w('try:')
i()
w('booking = get_object_or_404(Booking, id=booking_id, hostel=hostel)')
w('booking.booking_status = "Checked Out"')
w('booking.save()')
w('return JsonResponse({"success": True})')
d()
w('except Exception as e:')
i()
w('return JsonResponse({"error": str(e)}, status=400)')
d()
d()

# ===== Password Reset =====
w('')
w('@require_http_methods(["GET", "POST"])')
w('def forgot_password(request):')
i()
w('if request.method == "POST":')
i()
w('form = ForgotPasswordForm(request.POST)')
w('if form.is_valid():')
i()
w('email = form.cleaned_data["email"]')
w('try:')
i()
w('user = User.objects.get(email=email)')
w('from .email_utils import send_password_reset_email')
w('send_password_reset_email(user, request)')
d()
w('except User.DoesNotExist: pass')
w('messages.success(request, "If an account with that email exists, a reset link has been sent.")')
w('return redirect("login")')
d()
d()
w('else: form = ForgotPasswordForm()')
w('return render(request, "forgot_password.html", {"form": form})')
d()

w('')
w('@require_http_methods(["GET", "POST"])')
w('def reset_password(request, token):')
i()
w('try:')
i()
w('reset_token = PasswordResetToken.objects.select_related("user").get(token=token)')
d()
w('except PasswordResetToken.DoesNotExist:')
i()
w('return render(request, "password_reset_status.html", {"status": "invalid", "message": "Invalid reset link."})')
d()
w('if reset_token.is_expired:')
i()
w('return render(request, "password_reset_status.html", {"status": "expired", "message": "This reset link has expired."})')
d()
w('if reset_token.is_used:')
i()
w('return render(request, "password_reset_status.html", {"status": "used", "message": "This link has already been used."})')
d()
w('if request.method == "POST":')
i()
w('form = ResetPasswordForm(request.POST)')
w('if form.is_valid():')
i()
w('user = reset_token.user')
