#!/usr/bin/env python3
"""Generate the COMPLETE views.py for EHostelFinder in one shot."""
import os, py_compile
os.chdir(r'c:\Users\user\ehostelfinder')

lines = []
indent = 0

def w(s):
    if indent:
        lines.append('    ' * indent + s)
    else:
        lines.append(s)
def i(n=1):
    global indent; indent += n
def d(n=1):
    global indent; indent -= n

# ========== IMPORTS ==========
w('from django.shortcuts import render, get_object_or_404, redirect')
w('from django.contrib.auth import logout')
w('from django.http import JsonResponse')
w('from django.views.decorators.http import require_http_methods')
w('from django.views.decorators.csrf import csrf_exempt')
w('from django.contrib import messages')
w('from django.db.models import Avg')
w('from django.core.paginator import Paginator')
w('from django.utils import timezone')
w('from django.contrib.auth.decorators import login_required')
w('import json, os, urllib.request, urllib.error, uuid')
w('from .forms import UserRegistrationForm, UserLoginForm, ForgotPasswordForm, ResetPasswordForm, ProfileUpdateForm, HostelUploadForm')
w('from .models import Hostel, User, ContactMessage, Profile, Room, Booking, Review, Favorite, Message, Notification, Payment, RoomStatus, BookingStatus')
w('from .local_ai import get_local_ai_response')
w('')
w('KAMPALA_AREA_UNIVERSITIES = ["Makerere University", "Makerere University Business School", "Kyambogo University", "Kampala International University", "Uganda Christian University", "Ndejje University", "Bugema University", "Cavendish University Uganda", "St. Lawrence University Uganda", "Mutesa I Royal University"]')
w('')

# ========== get_university_options ==========
w('def get_university_options():')
i()
w('university_names, seen = [], set()')
w('def normalize(name):')
i()
w('if not name: return ""')
w('n = name.strip().lower()')
w('if "makerere" in n and "business school" in n: return "Makerere University Business School"')
w('if "makerere" in n: return "Makerere University"')
w('return name.strip()')
d()
w('for name in KAMPALA_AREA_UNIVERSITIES + list(Hostel.objects.exclude(university="").values_list("university", flat=True)):')
i()
w('if name:')
i()
w('normalized = normalize(name)')
w('if normalized.lower() not in seen:')
i()
w('university_names.append(normalized)')
w('seen.add(normalized.lower())')
d(3)
w('return [{"name": n} for n in university_names]')
d()
w('')

# ========== home ==========
w('def home(request):')
i()
w('university = request.GET.get("university", "All Universities")')
w('city = request.GET.get("city", "")')
w('country = request.GET.get("country", "")')
w('min_price = request.GET.get("min_price", "")')
w('max_price = request.GET.get("max_price", "")')
w('sort_by = request.GET.get("sort", "-created_at")')
w('page = request.GET.get("page", 1)')
w('valid_sorts = ["name", "-name", "price", "-price", "rating", "-rating", "created_at", "-created_at"]')
w('if sort_by not in valid_sorts: sort_by = "-created_at"')
w('hostels = Hostel.objects.all()')
w('if university and university != "All Universities": hostels = hostels.filter(university=university)')
w('if city: hostels = hostels.filter(city__icontains=city)')
w('if country: hostels = hostels.filter(country__icontains=country)')
w('if min_price:')
i()
w('try: hostels = hostels.filter(price__gte=float(min_price)).distinct()')
w('except ValueError: pass')
d()
w('if max_price:')
i()
w('try: hostels = hostels.filter(price__lte=float(max_price)).distinct()')
w('except ValueError: pass')
d()
w('hostels = hostels.order_by(sort_by)')
w('paginator = Paginator(hostels, 12)')
w('try: page_obj = paginator.page(page)')
w('except: page_obj = paginator.page(1)')
w('cities_list = sorted(Hostel.objects.values_list("city", flat=True).exclude(city="").distinct())')
w('countries_list = sorted(Hostel.objects.values_list("country", flat=True).exclude(country="").distinct())')
w('universities = get_university_options()')
w('rated_hostels = Hostel.objects.exclude(rating__isnull=True)')
w('avg_rating = round(sum(float(h.rating) for h in rated_hostels) / rated_hostels.count(), 1) if rated_hostels.exists() else 0.0')
w('hostel_list = []')
w('for h in page_obj:')
i()
w('cover = h.images.filter(is_cover=True).first()')
w('available_room = h.rooms.filter(status="Available").first()')
w('hostel_list.append({')
w('"id": str(h.id), "name": h.name, "description": h.description, "city": h.city, "country": h.country,')
w('"university": h.university, "image_url": h.image_url or (cover.image_url if cover else None),')
w('"facilities": [{"name": f.facility_name, "icon": f.icon or ""} for f in h.facilities.all()],')
w('"available": h.available, "rating": float(h.rating) if h.rating else round(float(h.average_rating), 1),')
w('"distance": h.distance or "Near campus",')
w('"price": str(h.price) if h.price else (str(available_room.price_per_night) if available_room else "0"),')
w('"amenities": h.amenities or [],')
w('})')
d()
w('favorite_ids = []')
w('if request.user.is_authenticated:')
i()
w('favorite_ids = list(Favorite.objects.filter(customer=request.user).values_list("hostel_id", flat=True))')
d()
w('return render(request, "home.html", {')
w('"hostels": hostel_list, "cities": cities_list, "countries": countries_list, "universities": universities,')
w('"selected_city": city, "selected_country": country, "selected_university": university, "selected_sort": sort_by,')
w('"total_hostels": Hostel.objects.count(), "total_universities": len(universities), "avg_rating": avg_rating,')
w('"total_cities": len(cities_list), "page_obj": page_obj, "favorite_ids": [str(fid) for fid in favorite_ids],')
w('})')
d()
w('')

# ========== hostel_detail ==========
w('def hostel_detail(request, id):')
i()
w('try:')
i()
w('hostel = get_object_or_404(Hostel, id=id)')
w('rooms = Room.objects.filter(hostel=hostel, status="Available")')
w('images = hostel.images.all()')
w('cover = hostel.images.filter(is_cover=True).first()')
w('facilities = hostel.facilities.all()')
w('reviews = hostel.reviews.select_related("customer").all()')
w('rooms_data = []')
w('for r in rooms:')
i()
w('rooms_data.append({')
w('"id": str(r.id), "room_number": r.room_number, "room_name": r.room_name, "room_type": r.room_type,')
w('"capacity": r.capacity, "available_quantity": r.available_quantity, "price_per_night": str(r.price_per_night),')
w('"floor": r.floor or 1, "description": r.description,')
w('"private_bathroom": r.private_bathroom, "air_conditioning": r.air_conditioning,')
w('"balcony": r.balcony, "television": r.television, "wifi": r.wifi,')
w('"images": [ri.image_url for ri in r.images.all()],')
w('})')
d()
w('reviews_data = []')
w('for rv in reviews:')
i()
w('reviews_data.append({')
w('"id": str(rv.id), "customer_name": rv.customer.get_full_name() or rv.customer.email,')
w('"rating": rv.rating, "comment": rv.comment,')
w('"created_at": rv.created_at.strftime("%Y-%m-%d"),')
w('})')
d()
w('context = {')
w('"hostel": {')
w('"id": str(hostel.id), "name": hostel.name, "description": hostel.description,')
w('"address": hostel.address, "city": hostel.city, "country": hostel.country,')
w('"university": hostel.university, "distance": hostel.distance or "Near campus",')
w('"price": float(hostel.price) if hostel.price else 0,')
w('"rating": float(hostel.rating) if hostel.rating else round(float(hostel.average_rating), 1),')
w('"available": hostel.available, "contact": hostel.contact or "",')
w('"amenities": hostel.amenities or [], "phone": hostel.phone, "email": hostel.email,')
w('"latitude": str(hostel.latitude) if hostel.latitude else None,')
w('"longitude": str(hostel.longitude) if hostel.longitude else None,')
w('"cover_image": cover.image_url if cover else None,')
w('"images": [{"url": img.image_url, "is_cover": img.is_cover} for img in images],')
w('},')
w('"rooms": rooms_data,')
w('"facilities": [{"name": f.facility_name, "icon": f.icon or ""} for f in facilities],')
w('"reviews": reviews_data,')
w('}')
d()
w('except Exception as e:')
i()
w('print(f"Error in hostel_detail: {e}")')
w('messages.error(request, "Error loading hostel details")')
w('return redirect("home")')
d()
w('if request.method == "POST" and "review_submit" in request.POST:')
i()
w('if not request.user.is_authenticated:')
i()
w('messages.error(request, "You must be logged in to leave a review")')
w('return redirect("login")')
d()
w('rating = request.POST.get("rating", "").strip()')
w('comment = request.POST.get("comment", "").strip()')
w('if not rating or not rating.isdigit() or int(rating) not in range(1, 6):')
i()
w('messages.error(request, "Please select a valid rating from 1 to 5.")')
w('return redirect("hostel_detail", id=hostel.id)')
d()
w('Review.objects.create(hostel=hostel, customer=request.user, rating=int(rating), comment=comment)')
w('hostel.review_count = hostel.reviews.count()')
w('hostel.rating = round(hostel.reviews.aggregate(avg=Avg("rating"))["avg"] or 0, 2)')
w('hostel.save(update_fields=["review_count", "rating"])')
w('messages.success(request, "Your review has been submitted successfully.")')
w('return redirect("hostel_detail", id=hostel.id)')
d()
w('return render(request, "hostel_detail.html", context)')
d()
w('')

# ========== API endpoints ==========
w('@require_http_methods(["GET"])')
w('def api_hostels(request):')
i()
w('city = request.GET.get("city", ""); country = request.GET.get("country", "")')
w('room_type = request.GET.get("room_type", ""); university = request.GET.get("university", "")')
w('min_price = request.GET.get("min_price", ""); max_price = request.GET.get("max_price", "")')
w('hostels = Hostel.objects.all()')
w('if city: hostels = hostels.filter(city__icontains=city)')
w('if country: hostels = hostels.filter(country__icontains=country)')
w('if university: hostels = hostels.filter(university=university)')
w('if room_type: hostels = hostels.filter(rooms__room_type=room_type).distinct()')
w('if min_price:')
i()
w('try: hostels = hostels.filter(price__gte=float(min_price)).distinct()')
w('except: pass')
d()
w('if max_price:')
i()
w('try: hostels = hostels.filter(price__lte=float(max_price)).distinct()')
w('except: pass')
d()
w('results = []')
w('for h in hostels:')
i()
w('cover = h.images.filter(is_cover=True).first()')
w('results.append({"id": str(h.id), "name": h.name, "city": h.city, "country": h.country, "university": h.university, "address": h.address, "description": h.description, "average_rating": round(float(h.average_rating), 2), "rating": float(h.rating) if h.rating else round(float(h.average_rating), 2), "review_count": h.reviews.count(), "image_url": h.image_url or (cover.image_url if cover else None), "facilities": [f.facility_name for f in h.facilities.all()], "amenities": h.amenities or [], "distance": h.distance or "", "price": float(h.price) if h.price else 0, "contact": h.contact or "", "available": h.available})')
d()
w('return JsonResponse(results, safe=False)')
d()
w('')
w('@require_http_methods(["GET"])')
w('def api_hostel_detail(request, id):')
i()
w('hostel = get_object_or_404(Hostel, id=id)')
w('rooms = Room.objects.filter(hostel=hostel)')
w('cover = hostel.images.filter(is_cover=True).first()')
w('rooms_data = [{"id": str(r.id), "room_number": r.room_number, "room_name": r.room_name, "room_type": r.room_type, "capacity": r.capacity, "price_per_night": str(r.price_per_night), "description": r.description, "private_bathroom": r.private_bathroom, "air_conditioning": r.air_conditioning, "wifi": r.wifi, "status": r.status} for r in rooms]')
w('return JsonResponse({"id": str(hostel.id), "name": hostel.name, "description": hostel.description, "address": hostel.address, "city": hostel.city, "country": hostel.country, "phone": hostel.phone, "email": hostel.email, "latitude": str(hostel.latitude) if hostel.latitude else None, "longitude": str(hostel.longitude) if hostel.longitude else None, "image_url": cover.image_url if cover else None, "rooms": rooms_data, "facilities": [{"name": f.facility_name} for f in hostel.facilities.all()]})')
d()
w('')
w('@require_http_methods(["GET"])')
w('def api_cities(request):')
i()
w('return JsonResponse(sorted(Hostel.objects.values_list("city", flat=True).exclude(city="").distinct()), safe=False)')
d()
w('')
w('@require_http_methods(["GET"])')
w('def api_countries(request):')
i()
w('return JsonResponse(sorted(Hostel.objects.values_list("country", flat=True).exclude(country="").distinct()), safe=False)')
d()
w('')

# ========== Auth ==========
w('@require_http_methods(["GET", "POST"])')
w('def login(request):')
i()
w('if request.method == "GET": return render(request, "login.html", {"form": UserLoginForm()})')
w('form = UserLoginForm(request.POST)')
w('if form.is_valid():')
i()
w('from django.contrib.auth import authenticate, login as auth_login')
w('user = authenticate(request, username=form.cleaned_data["email"], password=form.cleaned_data["password"])')
w('if user:')
i()
w('auth_login(request, user); return redirect("home")')
d()
w('messages.error(request, "Invalid email or password")')
d()
w('else: messages.error(request, "Invalid email or password")')
w('return render(request, "login.html", {"form": form})')
d()
w('')
w('@require_http_methods(["GET", "POST"])')
w('def signup(request):')
i()
w('if request.method == "POST":')
i()
w('form = UserRegistrationForm(request.POST)')
w('if form.is_valid():')
i()
w('user = form.save()')
w('try:')
i()
w('from .email_utils import send_email_confirmation')
w('send_email_confirmation(user, request)')
d()
w('except: pass')
d()
w('messages.success(request, "Account created! Please check your email to confirm.")')
w('return redirect("login")')
d()
d()
w('else: form = UserRegistrationForm()')
w('return render(request, "signup.html", {"form": form})')
d()
w('')
w('@require_http_methods(["GET"])')
w('def logout_view(request):')
i()
w('logout(request); return redirect("home")')
d()
w('')
w('def cookie_policy(request): return render(request, "cookie_policy.html")')
w('def privacy_policy(request): return render(request, "privacy_policy.html")')
w('def terms_of_use(request): return render(request, "terms_of_use.html")')
w('def ai_assistant(request): return render(request, "ai_assistant.html")')
w('def how_it_works(request): return render(request, "how_it_works.html")')
w('')

# ========== User / Booking / Message APIs ==========
w('@require_http_methods(["GET"])')
w('def admin_messages(request):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('msgs = ContactMessage.objects.all()[:100]')
w('return JsonResponse({"messages": [{"id": msg.id, "full_name": msg.full_name, "email": msg.email, "subject": msg.subject, "message": msg.message, "created_at": msg.created_at.isoformat(), "is_read": msg.is_read} for msg in msgs]})')
d()
w('')
w('@require_http_methods(["GET", "POST"])')
w('def get_user(request):')
i()
w('if request.user.is_authenticated:')
i()
w('p = getattr(request.user, "profile", None)')
w('return JsonResponse({"id": request.user.id, "email": request.user.email, "first_name": request.user.first_name, "last_name": request.user.last_name, "profile_image_url": p.profile_photo if p else None, "role": p.role if p else "customer", "full_name": p.full_name if p else ""})')
d()
w('return JsonResponse({"error": "Not authenticated"}, status=401)')
d()
w('')
w('@require_http_methods(["POST"])')
w('def create_booking(request):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('try:')
i()
w('data = json.loads(request.body)')
w('room = get_object_or_404(Room, id=data.get("room_id"))')
w('from datetime import datetime')
w('check_in = datetime.strptime(data.get("check_in"), "%Y-%m-%d").date()')
w('check_out = datetime.strptime(data.get("check_out"), "%Y-%m-%d").date()')
w('guests = int(data.get("guests", 1))')
w('nights = (check_out - check_in).days')
w('if nights <= 0: return JsonResponse({"error": "Invalid date range"}, status=400)')
w('total_price = room.price_per_night * nights')
w('booking = Booking.objects.create(hostel_id=room.hostel_id, room=room, customer_id=request.user.id, check_in=check_in, check_out=check_out, guests=guests, nights=nights, total_price=total_price, special_requests=data.get("special_requests", ""), booking_status="Pending", payment_status="Pending")')
w('Notification.objects.create(user=request.user, title="Booking Created", message=f"Booking at {room.hostel.name} (Ref: {booking.booking_reference}) created.")')
w('return JsonResponse({"id": str(booking.id), "booking_reference": booking.booking_reference, "hostel_id": str(booking.hostel_id), "room_id": str(booking.room_id), "check_in": booking.check_in.isoformat(), "check_out": booking.check_out.isoformat(), "guests": booking.guests, "nights": booking.nights, "total_price": str(booking.total_price), "booking_status": booking.booking_status, "payment_status": booking.payment_status, "special_requests": booking.special_requests}, status=201)')
d()
w('except Exception as e: return JsonResponse({"error": str(e)}, status=400)')
d()
w('')
w('@require_http_methods(["GET"])')
w('def get_booking_by_id(request, id):')
i()
w('try:')
i()
w('booking = get_object_or_404(Booking, id=id)')
w('if request.user.id == booking.customer_id:')
i()
w('return JsonResponse({"id": str(booking.id), "booking_reference": booking.booking_reference, "hostel_id": str(booking.hostel_id), "room_id": str(booking.room_id), "check_in": booking.check_in.isoformat(), "check_out": booking.check_out.isoformat(), "guests": booking.guests, "nights": booking.nights, "total_price": str(booking.total_price), "booking_status": booking.booking_status, "payment_status": booking.payment_status, "special_requests": booking.special_requests})')
d()
w('return JsonResponse({"error": "Not authorized"}, status=403)')
d()
w('except Exception as e: return JsonResponse({"error": str(e)}, status=500)')
d()
w('')
w('@require_http_methods(["POST"])')
w('def create_message(request):')
i()
w('try:')
i()
w('data = json.loads(request.body)')
w('hostel = get_object_or_404(Hostel, id=data.get("hostelId"))')
w('msg = Message.objects.create(hostel=hostel, user=request.user if request.user.is_authenticated else None, full_name=data.get("fullName", ""), email=data.get("email", ""), phone=data.get("phone", ""), subject=data.get("subject", ""), content=data.get("content", "") or data.get("message", ""))')
w('return JsonResponse({"id": str(msg.id), "hostel_id": str(msg.hostel_id), "full_name": msg.full_name, "email": msg.email, "subject": msg.subject, "message": msg.content, "created_at": msg.created_at.isoformat()}, status=201)')
d()
w('except Exception as e: return JsonResponse({"error": str(e)}, status=500)')
d()
w('')
w('@csrf_exempt')
w('@require_http_methods(["POST"])')
w('def ai_chat(request):')
i()
w('try:')
i()
w('data = json.loads(request.body)')
w('question = data.get("question", "").strip()')
w('if not question: return JsonResponse({"error": "Question is required."}, status=400)')
w('api_key = os.getenv("GOOGLE_GENERATIVE_API_KEY")')
w('if api_key:')
i()
w('try:')
i()
w('prompt = f"You are a helpful hostel assistant for EHostelFinder. Question: {question}"')
w('payload = json.dumps({"contents": [{"parts": [{"text": prompt}]}]}).encode("utf-8")')
w('url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={api_key}"')
w('req = urllib.request.Request(url, data=payload, headers={"Content-Type": "application/json"}, method="POST")')
w('with urllib.request.urlopen(req, timeout=30) as resp:')
i()
w('return JsonResponse(json.loads(resp.read().decode("utf-8")))')
d()
d()
w('except: pass')
d()
w('return JsonResponse({"candidates": [{"content": {"parts": [{"text": get_local_ai_response(question)}]}}]})')
d()
w('except Exception as e: return JsonResponse({"error": str(e)}, status=500)')
d()
w('')
w('@require_http_methods(["GET"])')
w('def get_messages_by_hostel(request, hostel_id):')
i()
w('try:')
i()
w('msgs = Message.objects.filter(hostel_id=hostel_id)')
w('return JsonResponse([{"id": str(m.id), "hostel_id": str(m.hostel_id), "full_name": m.full_name, "email": m.email, "subject": m.subject, "message": m.content, "created_at": m.created_at.isoformat()} for m in msgs], safe=False)')
d()
w('except Exception as e: return JsonResponse({"error": str(e)}, status=500)')
d()
w('')
w('@require_http_methods(["GET"])')
w('def universities(request):')
i()
w('university_options = get_university_options()')
w('universities_data = []')
w('for uni in university_options:')
i()
w('name = uni["name"]')
w('count = Hostel.objects.filter(university=name).count()')
w('top = Hostel.objects.filter(university=name).order_by("-rating").first()')
w('universities_data.append({"name": name, "count": count, "top_hostel": top.name if top else "", "rating": float(top.rating) if top and top.rating else 0})')
d()
w('universities_data.sort(key=lambda x: x["name"])')
w('return render(request, "universities.html", {"universities": universities_data})')
d()
w('')
w('@csrf_exempt')
w('def contact(request):')
i()
w('if request.method == "POST":')
i()
w('try:')
i()
w('ContactMessage.objects.create(full_name=request.POST.get("name", ""), email=request.POST.get("email", ""), subject=request.POST.get("subject", ""), message=request.POST.get("message", ""))')
w('return JsonResponse({"success": True, "message": "Message sent successfully!"})')
d()
w('except Exception as e: return JsonResponse({"error": str(e)}, status=400)')
d()
w('return render(request, "contact.html")')
d()
w('')
w('def google_auth(request):')
i()
w('import urllib.parse; from django.conf import settings')
w('redirect_uri = request.build_absolute_uri("/api/auth/google/callback/")')
w('params = {"client_id": settings.GOOGLE_CLIENT_ID, "redirect_uri": redirect_uri, "response_type": "code", "scope": "email profile", "access_type": "online"}')
w('return redirect(f"https://accounts.google.com/o/oauth2/auth?{urllib.parse.urlencode(params)}")')
d()
w('')
w('def google_auth_callback(request):')
i()
w('import urllib.parse, urllib.request; from django.conf import settings')
w('from django.contrib.auth import login as auth_login')
w('code = request.GET.get("code")')
w('if not code: messages.error(request, "Google auth failed"); return redirect("login")')
w('redirect_uri = request.build_absolute_uri("/api/auth/google/callback/")')
w('token_data = urllib.parse.urlencode({"code": code, "client_id": settings.GOOGLE_CLIENT_ID, "client_secret": settings.GOOGLE_CLIENT_SECRET, "redirect_uri": redirect_uri, "grant_type": "authorization_code"}).encode()')
w('try:')
i()
w('req = urllib.request.Request("https://oauth2.googleapis.com/token", data=token_data, method="POST")')
w('req.add_header("Content-Type", "application/x-www-form-urlencoded")')
w('with urllib.request.urlopen(req, timeout=10) as resp:')
i()
w('token_result = json.loads(resp.read().decode())')
d()
w('access_token = token_result.get("access_token")')
w('user_req = urllib.request.Request(f"https://www.googleapis.com/oauth2/v2/userinfo?access_token={access_token}")')
w('with urllib.request.urlopen(user_req, timeout=10) as resp:')
i()
w('user_info = json.loads(resp.read().decode())')
d()
w('email = user_info.get("email")')

# WRITE
with open('hostels/views.py', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

try:
    py_compile.compile('hostels/views.py', doraise=True)
    print(f'PART 1 SUCCESS: {len(lines)} lines written, syntax OK')
except py_compile.PyCompileError as e:
    print(f'SYNTAX ERROR in PART 1: {e}')
