#!/usr/bin/env python3
"""Generate views.py - Part 3: API endpoints and remaining views."""
import os, py_compile
os.chdir(r'c:\Users\user\ehostelfinder')

with open('hostels/views.py', 'r') as f:
    existing = f.read()

lines = existing.split('\n')
while lines and lines[-1] == '':
    lines.pop()

indent = 0
def w(s):
    if indent:
        lines.append('    ' * indent + s)
    else:
        lines.append(s)
def i(n=1):
    global indent; indent += n
def d(n=1):
    global indent; indent -= n

w('')
w('')
w('@require_http_methods(["GET"])')
w('def api_hostels(request):')
i()
w('city = request.GET.get("city", ""); country = request.GET.get("country", "")')
w('room_type = request.GET.get("room_type", ""); university = request.GET.get("university", "")')
w('min_price = request.GET.get("min_price", ""); max_price = request.GET.get("max_price", "")')
w('hostels = Hostel.objects.all()')
w('if city: hostels = hostels.filter(city__icontains=city)')
w('if country: hostels = hostels.filter(country__icontains=country)')
w('if university: hostels = hostels.filter(university=university)')
w('if room_type: hostels = hostels.filter(rooms__room_type=room_type).distinct()')
w('if min_price:')
i()
w('try: hostels = hostels.filter(price__gte=float(min_price)).distinct()')
w('except ValueError: pass')
d()
w('if max_price:')
i()
w('try: hostels = hostels.filter(price__lte=float(max_price)).distinct()')
w('except ValueError: pass')
d()
w('results = []')
w('for h in hostels:')
i()
w('cover = h.images.filter(is_cover=True).first()')
w('results.append({')
w('"id": str(h.id), "name": h.name, "city": h.city, "country": h.country,')
w('"university": h.university, "address": h.address, "description": h.description,')
w('"average_rating": round(float(h.average_rating), 2),')
w('"rating": float(h.rating) if h.rating else round(float(h.average_rating), 2),')
w('"review_count": h.reviews.count(),')
w('"image_url": h.image_url or (cover.image_url if cover else None),')
w('"facilities": [f.facility_name for f in h.facilities.all()],')
w('"amenities": h.amenities or [],')
w('"distance": h.distance or "", "price": float(h.price) if h.price else 0,')
w('"contact": h.contact or "", "available": h.available,')
w('})')
d()
w('return JsonResponse(results, safe=False)')
d()
w('')
w('')
w('@require_http_methods(["GET"])')
w('def api_hostel_detail(request, id):')
i()
w('hostel = get_object_or_404(Hostel, id=id)')
w('rooms = Room.objects.filter(hostel=hostel)')
w('cover = hostel.images.filter(is_cover=True).first()')
w('rooms_data = [{"id": str(r.id), "room_number": r.room_number, "room_name": r.room_name, "room_type": r.room_type, "capacity": r.capacity, "price_per_night": str(r.price_per_night), "description": r.description, "private_bathroom": r.private_bathroom, "air_conditioning": r.air_conditioning, "wifi": r.wifi, "status": r.status} for r in rooms]')
w('return JsonResponse({"id": str(hostel.id), "name": hostel.name, "description": hostel.description, "address": hostel.address, "city": hostel.city, "country": hostel.country, "phone": hostel.phone, "email": hostel.email, "latitude": str(hostel.latitude) if hostel.latitude else None, "longitude": str(hostel.longitude) if hostel.longitude else None, "image_url": cover.image_url if cover else None, "rooms": rooms_data, "facilities": [{"name": f.facility_name} for f in hostel.facilities.all()]})')
d()
w('')
w('')
w('@require_http_methods(["GET"])')
w('def api_cities(request):')
i()
w('return JsonResponse(sorted(Hostel.objects.values_list("city", flat=True).exclude(city="").distinct()), safe=False)')
d()
w('')
w('')
w('@require_http_methods(["GET"])')
w('def api_countries(request):')
i()
w('return JsonResponse(sorted(Hostel.objects.values_list("country", flat=True).exclude(country="").distinct()), safe=False)')
d()
w('')
w('')
w('@require_http_methods(["GET", "POST"])')
w('def login(request):')
i()
w('if request.method == "GET":')
i()
w('return render(request, "login.html", {"form": UserLoginForm()})')
d()
w('form = UserLoginForm(request.POST)')
w('if form.is_valid():')
i()
w('from django.contrib.auth import authenticate, login as auth_login')
w('user = authenticate(request, username=form.cleaned_data["email"], password=form.cleaned_data["password"])')
w('if user:')
i()
w('auth_login(request, user)')
w('return redirect("home")')
d()
w('messages.error(request, "Invalid email or password")')
d()
w('else:')
i()
w('messages.error(request, "Invalid email or password")')
d()
w('return render(request, "login.html", {"form": form})')
d()
w('')
w('')
w('@require_http_methods(["GET", "POST"])')
w('def signup(request):')
i()
w('if request.method == "POST":')
i()
w('form = UserRegistrationForm(request.POST)')
w('if form.is_valid():')
i()
w('user = form.save()')
w('try:')
i()
w('from .email_utils import send_email_confirmation')
w('send_email_confirmation(user, request)')
d()
w('except Exception: pass')
w('messages.success(request, "Account created! Please check your email to confirm.")')
w('return redirect("login")')
d()
d()
w('else:')
i()
w('form = UserRegistrationForm()')
d()
w('return render(request, "signup.html", {"form": form})')
d()
w('')
w('')
w('@require_http_methods(["GET"])')
w('def logout_view(request):')
i()
w('logout(request); return redirect("home")')
d()
w('')
w('')
w('def cookie_policy(request): return render(request, "cookie_policy.html")')
w('def privacy_policy(request): return render(request, "privacy_policy.html")')
w('def terms_of_use(request): return render(request, "terms_of_use.html")')
w('def ai_assistant(request): return render(request, "ai_assistant.html")')
w('def how_it_works(request): return render(request, "how_it_works.html")')
w('')
w('')
w('@require_http_methods(["GET"])')
w('def admin_messages(request):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('msgs = ContactMessage.objects.all()[:100]')
w('return JsonResponse({"messages": [{"id": msg.id, "full_name": msg.full_name, "email": msg.email, "subject": msg.subject, "message": msg.message, "created_at": msg.created_at.isoformat(), "is_read": msg.is_read} for msg in msgs]})')
d()
w('')
w('')
w('@require_http_methods(["GET", "POST"])')
w('def get_user(request):')
i()
w('if request.user.is_authenticated:')
i()
w('p = getattr(request.user, "profile", None)')
w('return JsonResponse({"id": request.user.id, "email": request.user.email, "first_name": request.user.first_name, "last_name": request.user.last_name, "profile_image_url": p.profile_photo if p else None, "role": p.role if p else "customer", "full_name": p.full_name if p else ""})')
d()
w('return JsonResponse({"error": "Not authenticated"}, status=401)')
d()
w('')
w('')
w('@require_http_methods(["POST"])')
w('def create_booking(request):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('try:')
i()
w('data = json.loads(request.body)')
w('room = get_object_or_404(Room, id=data.get("room_id"))')
w('from datetime import datetime')
w('check_in = datetime.strptime(data.get("check_in"), "%Y-%m-%d").date()')
w('check_out = datetime.strptime(data.get("check_out"), "%Y-%m-%d").date()')
w('guests = int(data.get("guests", 1))')
w('nights = (check_out - check_in).days')
w('if nights <= 0: return JsonResponse({"error": "Invalid date range"}, status=400)')
w('total_price = room.price_per_night * nights')
w('booking = Booking.objects.create(hostel_id=room.hostel_id, room=room, customer_id=request.user.id, check_in=check_in, check_out=check_out, guests=guests, nights=nights, total_price=total_price, special_requests=data.get("special_requests", ""), booking_status="Pending", payment_status="Pending")')
w('Notification.objects.create(user=request.user, title="Booking Created", message=f"Booking at {room.hostel.name} (Ref: {booking.booking_reference}) created.")')
w('return JsonResponse({"id": str(booking.id), "booking_reference": booking.booking_reference, "hostel_id": str(booking.hostel_id), "room_id": str(booking.room_id), "check_in": booking.check_in.isoformat(), "check_out": booking.check_out.isoformat(), "guests": booking.guests, "nights": booking.nights, "total_price": str(booking.total_price), "booking_status": booking.booking_status, "payment_status": booking.payment_status, "special_requests": booking.special_requests}, status=201)')
d()
w('except Exception as e: return JsonResponse({"error": str(e)}, status=400)')
d()
w('')
w('')
w('@require_http_methods(["GET"])')
w('def get_booking_by_id(request, id):')
i()
w('try:')
i()
w('booking = get_object_or_404(Booking, id=id)')
w('if request.user.id == booking.customer_id:')
i()
w('return JsonResponse({"id": str(booking.id), "booking_reference": booking.booking_reference, "hostel_id": str(booking.hostel_id), "room_id": str(booking.room_id), "check_in": booking.check_in.isoformat(), "check_out": booking.check_out.isoformat(), "guests": booking.guests, "nights": booking.nights, "total_price": str(booking.total_price), "booking_status": booking.booking_status, "payment_status": booking.payment_status, "special_requests": booking.special_requests})')
d()
w('return JsonResponse({"error": "Not authorized"}, status=403)')
d()
w('except Exception as e: return JsonResponse({"error": str(e)}, status=500)')
d()
w('')
w('')
w('@require_http_methods(["POST"])')
w('def create_message(request):')
i()
w('try:')
i()
w('data = json.loads(request.body)')
w('hostel = get_object_or_404(Hostel, id=data.get("hostelId"))')
w('msg = Message.objects.create(hostel=hostel, user=request.user if request.user.is_authenticated else None, full_name=data.get("fullName", ""), email=data.get("email", ""), phone=data.get("phone", ""), subject=data.get("subject", ""), content=data.get("content", "") or data.get("message", ""))')
w('return JsonResponse({"id": str(msg.id), "hostel_id": str(msg.hostel_id), "full_name": msg.full_name, "email": msg.email, "subject": msg.subject, "message": msg.content, "created_at": msg.created_at.isoformat()}, status=201)')
d()
w('except Exception as e: return JsonResponse({"error": str(e)}, status=500)')
d()
w('')
w('')
w('@csrf_exempt')
w('@require_http_methods(["POST"])')
w('def ai_chat(request):')
i()
w('try:')
i()
w('data = json.loads(request.body)')
w('question = data.get("question", "").strip()')
w('if not question: return JsonResponse({"error": "Question is required."}, status=400)')
w('api_key = os.getenv("GOOGLE_GENERATIVE_API_KEY")')
w('if api_key:')
i()
w('try:')
i()
w('prompt = f"You are a helpful hostel assistant for EHostelFinder. Be friendly, concise, and helpful. Question: {question}"')
w('payload = json.dumps({"contents": [{"parts": [{"text": prompt}]}]}).encode("utf-8")')
w('url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={api_key}"')
w('req = urllib.request.Request(url, data=payload, headers={"Content-Type": "application/json"}, method="POST")')
w('with urllib.request.urlopen(req, timeout=30) as resp:')
i()
w('return JsonResponse(json.loads(resp.read().decode("utf-8")))')
d()
d()
w('except Exception: pass')
d()
w('return JsonResponse({"candidates": [{"content": {"parts": [{"text": get_local_ai_response(question)}]}}]})')
d()
w('except Exception as e: return JsonResponse({"error": str(e)}, status=500)')
d()
w('')
w('')
w('@require_http_methods(["GET"])')
w('def get_messages_by_hostel(request, hostel_id):')
i()
w('try:')
i()
w('msgs = Message.objects.filter(hostel_id=hostel_id)')
w('return JsonResponse([{"id": str(m.id), "hostel_id": str(m.hostel_id), "full_name": m.full_name, "email": m.email, "subject": m.subject, "message": m.content, "created_at": m.created_at.isoformat()} for m in msgs], safe=False)')
d()
w('except Exception as e: return JsonResponse({"error": str(e)}, status=500)')
d()
w('')
w('')
w('@require_http_methods(["GET"])')
w('def universities(request):')
i()
w('university_options = get_university_options()')
w('universities_data = []')
w('for uni in university_options:')
i()
w('name = uni["name"]')
w('count = Hostel.objects.filter(university=name).count()')
w('top = Hostel.objects.filter(university=name).order_by("-rating").first()')
w('universities_data.append({"name": name, "count": count, "top_hostel": top.name if top else "", "rating": float(top.rating) if top and top.rating else 0})')
d()
w('universities_data.sort(key=lambda x: x["name"])')
w('return render(request, "universities.html", {"universities": universities_data})')
d()
w('')
w('')
w('@csrf_exempt')
w('def contact(request):')
i()
w('if request.method == "POST":')
i()
w('try:')
i()
w('ContactMessage.objects.create(full_name=request.POST.get("name", ""), email=request.POST.get("email", ""), subject=request.POST.get("subject", ""), message=request.POST.get("message", ""))')
w('return JsonResponse({"success": True, "message": "Message sent successfully!"})')
d()
w('except Exception as e: return JsonResponse({"error": str(e)}, status=400)')
d()
w('return render(request, "contact.html")')
d()
w('')
w('')
w('def google_auth(request):')
i()
w('import urllib.parse')
w('from django.conf import settings')
w('redirect_uri = request.build_absolute_uri("/api/auth/google/callback/")')
w('params = {"client_id": settings.GOOGLE_CLIENT_ID, "redirect_uri": redirect_uri, "response_type": "code", "scope": "email profile", "access_type": "online"}')
w('return redirect(f"https://accounts.google.com/o/oauth2/auth?{urllib.parse.urlencode(params)}")')
d()
w('')
w('')
w('def google_auth_callback(request):')
i()
w('import urllib.parse, urllib.request')
w('from django.conf import settings')
w('from django.contrib.auth import login as auth_login')
w('code = request.GET.get("code")')
w('if not code:')
i()
w('messages.error(request, "Google authentication failed")')
w('return redirect("login")')
d()
w('redirect_uri = request.build_absolute_uri("/api/auth/google/callback/")')
w('token_data = urllib.parse.urlencode({"code": code, "client_id": settings.GOOGLE_CLIENT_ID, "client_secret": settings.GOOGLE_CLIENT_SECRET, "redirect_uri": redirect_uri, "grant_type": "authorization_code"}).encode()')
w('try:')
i()
w('req = urllib.request.Request("https://oauth2.googleapis.com/token", data=token_data, method="POST")')
w('req.add_header("Content-Type", "application/x-www-form-urlencoded")')
w('with urllib.request.urlopen(req, timeout=10) as resp:')
i()
w('token_result = json.loads(resp.read().decode())')
d()
w('access_token = token_result.get("access_token")')
w('user_req = urllib.request.Request(f"https://www.googleapis.com/oauth2/v2/userinfo?access_token={access_token}")')
w('with urllib.request.urlopen(user_req, timeout=10) as resp:')
i()
w('user_info = json.loads(resp.read().decode())')
d()
w('email = user_info.get("email")')
w('first_name = user_info.get("given_name", "")')
w('last_name = user_info.get("family_name", "")')
w('try: user = User.objects.get(email=email)')
w('except User.DoesNotExist:')
i()
w('user = User.objects.create(id=str(uuid.uuid4()), email=email, first_name=first_name or email.split("@")[0], last_name=last_name, provider="google")')
d()
w('auth_login(request, user)')
w('return redirect("home")')
d()
w('except Exception as e:')
i()
w('messages.error(request, "Google authentication failed")')
w('return redirect("login")')
d()
d()
w('')
w('')
w('def manager_dashboard(request):')
i()
w('if not request.user.is_authenticated: return redirect("login")')
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "manager":')
i()
w('messages.error(request, "Access denied."); return redirect("home")')
d()
w('hostel = profile.hostel')
w('if not hostel:')
i()
w('messages.error(request, "No hostel assigned."); return redirect("home")')
d()
w('return render(request, "manager/dashboard.html", {"hostel": hostel})')
d()
w('')
w('')
w('@login_required')
w('def admin_manager_assign(request):')
i()
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "admin":')
i()
w('messages.error(request, "Access denied."); return redirect("home")')
d()
w('return render(request, "admin/manager_assign.html")')
d()
w('')
w('')
w('@login_required')
w('@require_http_methods(["GET", "POST"])')
w('def hostel_upload(request):')
i()
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "admin":')
i()
w('messages.error(request, "Access denied."); return redirect("home")')
d()
w('if request.method == "POST":')
i()
w('form = HostelUploadForm(request.POST)')
w('if form.is_valid():')
i()
w('hostel = Hostel.objects.create(name=form.cleaned_data["name"], description=form.cleaned_data["description"] or "", address=form.cleaned_data["address"], city=form.cleaned_data["city"], country=form.cleaned_data.get("country") or "Uganda", university=form.cleaned_data["university"] or "", distance="Near campus", price=form.cleaned_data["price_single"] or 0, rating=form.cleaned_data["rating"] or 0, amenities=[item.strip() for item in form.cleaned_data["amenities"].split(",") if item.strip()], image_url=form.cleaned_data["image_url"] or "")')
w('room_types = [("Single", form.cleaned_data["price_single"], request.POST.get("room_available_single")), ("Double", form.cleaned_data["price_double"], request.POST.get("room_available_double")), ("Triple", form.cleaned_data["price_triple"], request.POST.get("room_available_triple")), ("Quadruple", form.cleaned_data["price_quadruple"], request.POST.get("room_available_quadruple"))]')
w('for index, (room_type, price, is_avail) in enumerate(room_types, start=1):')
i()
w('if price is None or price == 0: continue')
w('capacity = 1 if room_type == "Single" else 2 if room_type == "Double" else 3 if room_type == "Triple" else 4')
w('Room.objects.create(hostel=hostel, room_number=str(index), room_name=f"{room_type} Room", room_type=room_type, capacity=capacity, available_quantity=1, price_per_night=price, is_available=is_avail == "on")')
d()
w('messages.success(request, "Hostel created successfully.")')
w('return redirect("hostel_upload")')
d()
d()
w('else:')
i()
w('form = HostelUploadForm()')
d()
w('return render(request, "admin/hostel_upload.html", {"form": form})')
d()
w('')
w('')
w('@require_http_methods(["GET"])')
w('def manager_bookings(request):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "manager": return JsonResponse({"error": "Access denied"}, status=403)')
w('hostel = profile.hostel')
w('if not hostel: return JsonResponse({"error": "No hostel assigned"}, status=400)')
w('bookings = Booking.objects.filter(hostel=hostel).select_related("customer", "room").order_by("-booked_at")')
w('return JsonResponse([{"id": str(b.id), "booking_reference": b.booking_reference, "customer_name": b.customer.get_full_name() or b.customer.email, "customer_email": b.customer.email, "room_number": b.room.room_number, "room_name": b.room.room_name, "check_in": b.check_in.isoformat(), "check_out": b.check_out.isoformat(), "guests": b.guests, "nights": b.nights, "total_price": str(b.total_price), "booking_status": b.booking_status, "payment_status": b.payment_status, "special_requests": b.special_requests or ""} for b in bookings], safe=False)')
d()
w('')
w('')
w('@require_http_methods(["POST"])')
w('def manager_update_booking(request, booking_id):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "manager": return JsonResponse({"error": "Access denied"}, status=403)')
w('hostel = profile.hostel')
w('if not hostel: return JsonResponse({"error": "No hostel assigned"}, status=400)')
w('try:')
i()
w('data = json.loads(request.body)')
w('booking = get_object_or_404(Booking, id=booking_id, hostel=hostel)')
w('status = data.get("booking_status")')
w('if status and status in dict(BookingStatus.choices).keys():')
i()
w('booking.booking_status = status')
w('booking.save(update_fields=["booking_status"])')
d()
w('return JsonResponse({"success": True})')
d()
w('except Exception as e: return JsonResponse({"error": str(e)}, status=400)')
d()
w('')
w('')
w('@require_http_methods(["GET", "POST"])')
w('def manager_checkins(request):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "manager": return JsonResponse({"error": "Access denied"}, status=403)')
w('hostel = profile.hostel')
w('if not hostel: return JsonResponse({"error": "No hostel assigned"}, status=400)')
w('if request.method == "GET":')
i()
w('bookings = Booking.objects.filter(hostel=hostel, booking_status="Checked In").select_related("customer", "room")')
w('return JsonResponse([{"id": str(b.id), "booking_reference": b.booking_reference, "customer_name": b.customer.get_full_name() or b.customer.email, "customer_email": b.customer.email, "room_number": b.room.room_number, "room_name": b.room.room_name, "check_in": b.check_in.isoformat(), "check_out": b.check_out.isoformat(), "guests": b.guests, "total_price": str(b.total_price)} for b in bookings], safe=False)')
d()
d()
w('')
w('')
w('@require_http_methods(["GET", "POST"])')
w('def manager_rooms(request):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "manager": return JsonResponse({"error": "Access denied"}, status=403)')
w('hostel = profile.hostel')
w('if not hostel: return JsonResponse({"error": "No hostel assigned"}, status=400)')
w('if request.method == "GET":')
i()
w('rooms = Room.objects.filter(hostel=hostel)')
w('return JsonResponse([{"id": str(r.id), "room_number": r.room_number, "room_name": r.room_name, "room_type": r.room_type, "capacity": r.capacity, "available_quantity": r.available_quantity, "price_per_night": str(r.price_per_night), "status": r.status, "is_available": r.is_available} for r in rooms], safe=False)')
d()
w('try:')
i()
w('data = json.loads(request.body)')
w('room_id = data.get("room_id")')
w('room = get_object_or_404(Room, id=room_id, hostel=hostel)')
w('status = data.get("status")')
w('if status and status in dict(RoomStatus.choices).keys():')
i()
w('room.status = status; room.is_available = status == "Available"')
d()
w('if data.get("is_available") is not None:')
i()
w('room.is_available = data.get("is_available") in [True, "true"]')
d()
w('if data.get("available_quantity") is not None:')
i()
w('room.available_quantity = int(data.get("available_quantity"))')
d()
w('room.save()')
w('return JsonResponse({"success": True})')
d()
w('except Exception as e: return JsonResponse({"error": str(e)}, status=400)')
d()
w('')
w('')
w('@csrf_exempt')
w('@require_http_methods(["POST"])')
w('def admin_assign_manager(request):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "admin": return JsonResponse({"error": "Access denied"}, status=403)')
w('try:')
i()
w('data = json.loads(request.body)')
w('manager_id, hostel_id = data.get("manager_id"), data.get("hostel_id")')
w('if not manager_id or not hostel_id: return JsonResponse({"error": "manager_id and hostel_id required"}, status=400)')
w('manager_profile = get_object_or_404(Profile, id=manager_id, role="manager")')
w('hostel = get_object_or_404(Hostel, id=hostel_id)')
w('manager_profile.hostel = hostel; manager_profile.save()')
w('return JsonResponse({"success": True, "message": f"Manager {manager_profile.full_name} assigned to {hostel.name}"})')
d()
w('except Exception as e: return JsonResponse({"error": str(e)}, status=400)')
d()
w('')
w('')
w('@require_http_methods(["POST"])')
w('def admin_remove_manager(request):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "admin": return JsonResponse({"error": "Access denied"}, status=403)')
w('try:')
i()
w('data = json.loads(request.body)')
w('manager_id = data.get("manager_id")')
w('if not manager_id: return JsonResponse({"error": "manager_id required"}, status=400)')
w('manager_profile = get_object_or_404(Profile, id=manager_id, role="manager")')
w('manager_profile.hostel = None; manager_profile.save()')
w('return JsonResponse({"success": True})')
d()
w('except Exception as e: return JsonResponse({"error": str(e)}, status=400)')
d()
w('')
w('')
w('@require_http_methods(["GET"])')
w('def api_managers(request):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "admin": return JsonResponse({"error": "Access denied"}, status=403)')
w('managers = Profile.objects.filter(role="manager").select_related("hostel")')
w('return JsonResponse([{"id": str(m.id), "full_name": m.full_name, "email": m.email, "hostel_id": str(m.hostel_id) if m.hostel else None, "hostel_name": m.hostel.name if m.hostel else None} for m in managers], safe=False)')
d()
w('')
w('')
w('@csrf_exempt')
w('@require_http_methods(["POST"])')
w('def admin_create_manager(request):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "admin": return JsonResponse({"error": "Access denied"}, status=403)')
w('try:')
i()
w('data = json.loads(request.body)')
w('full_name = data.get("full_name", "").strip()')
w('email = data.get("email", "").strip()')
w('phone = data.get("phone", "").strip()')
w('password = data.get("password", "")')
w('if not full_name or not email or not password: return JsonResponse({"error": "Full name, email, and password required"}, status=400)')
w('if len(password) < 8: return JsonResponse({"error": "Password must be at least 8 characters"}, status=400)')
w('if User.objects.filter(email=email).exists(): return JsonResponse({"error": "Email already exists"}, status=400)')
w('name_parts = full_name.split(" ", 1)')
w('first_name = name_parts[0] if name_parts else full_name')
w('last_name = name_parts[1] if len(name_parts) > 1 else ""')
w('user = User.objects.create(id=str(uuid.uuid4()), email=email, first_name=first_name, last_name=last_name, is_email_verified=True)')
w('user.set_password(password); user.save()')
w('Profile.objects.create(user=user, full_name=full_name, email=email, phone=phone or None, role="manager")')
w('return JsonResponse({"success": True, "message": f"Manager {full_name} created successfully"})')
d()
w('except Exception as e: return JsonResponse({"error": str(e)}, status=400)')
d()
w('')
w('')
w('@require_http_methods(["GET"])')
w('def api_unassigned_managers(request):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "admin": return JsonResponse({"error": "Access denied"}, status=403)')
w('managers = Profile.objects.filter(role="manager", hostel__isnull=True)')
w('return JsonResponse([{"id": str(m.id), "full_name": m.full_name, "email": m.email} for m in managers], safe=False)')
d()
w('')
w('')
w('@require_http_methods(["GET"])')
w('def api_hostel_managers(request, hostel_id):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "admin": return JsonResponse({"error": "Access denied"}, status=403)')
w('hostel = get_object_or_404(Hostel, id=hostel_id)')
w('managers = Profile.objects.filter(role="manager", hostel=hostel)')
w('return JsonResponse([{"id": str(m.id), "full_name": m.full_name, "email": m.email} for m in managers], safe=False)')
d()
w('')
w('')
w('@require_http_methods(["POST"])')
w('def manager_checkout(request, booking_id):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('profile = getattr(request.user, "profile", None)')
w('if not profile or profile.role != "manager": return JsonResponse({"error": "Access denied"}, status=403)')
w('hostel = profile.hostel')
w('if not hostel: return JsonResponse({"error": "No hostel assigned"}, status=400)')
w('try:')
i()
w('booking = get_object_or_404(Booking, id=booking_id, hostel=hostel)')
w('booking.booking_status = "Checked Out"; booking.save()')
w('return JsonResponse({"success": True})')
d()
w('except Exception as e: return JsonResponse({"error": str(e)}, status=400)')
d()
w('')
w('')
w('@require_http_methods(["GET", "POST"])')
w('def forgot_password(request):')
i()
w('if request.method == "POST":')
i()
w('form = ForgotPasswordForm(request.POST)')
w('if form.is_valid():')
i()
w('email = form.cleaned_data["email"]')
w('try:')
i()
w('user = User.objects.get(email=email)')
w('from .email_utils import send_password_reset_email')
w('send_password_reset_email(user, request)')
d()
w('except User.DoesNotExist: pass')
w('messages.success(request, "If an account with that email exists, a reset link has been sent.")')
w('return redirect("login")')
d()
d()
w('else: form = ForgotPasswordForm()')
w('return render(request, "forgot_password.html", {"form": form})')
d()
w('')
w('')
w('@require_http_methods(["GET", "POST"])')
w('def reset_password(request, token):')
i()
w('from .models import PasswordResetToken')
w('try: reset_token = PasswordResetToken.objects.select_related("user").get(token=token)')
w('except PasswordResetToken.DoesNotExist:')
i()
w('return render(request, "password_reset_status.html", {"status": "invalid", "message": "Invalid reset link."})')
d()
w('if reset_token.is_expired:')
i()
w('return render(request, "password_reset_status.html", {"status": "expired", "message": "This reset link has expired."})')
d()
w('if reset_token.is_used:')
i()
w('return render(request, "password_reset_status.html", {"status": "used", "message": "This link has already been used."})')
d()
w('if request.method == "POST":')
i()
w('form = ResetPasswordForm(request.POST)')
w('if form.is_valid():')
i()
w('user = reset_token.user')
w('user.set_password(form.cleaned_data["new_password"]); user.save()')
w('reset_token.used_at = timezone.now(); reset_token.save()')
w('messages.success(request, "Your password has been reset."); return redirect("login")')
d()
d()
w('else: form = ResetPasswordForm()')
w('return render(request, "reset_password.html", {"form": form, "token": token})')
d()
w('')
w('')
w('@login_required')
w('def profile(request):')
i()
w('user = request.user')
w('profile_obj = getattr(user, "profile", None)')
w('if request.method == "POST":')
i()
w('form = ProfileUpdateForm(request.POST, instance=profile_obj)')
w('if form.is_valid():')
i()
w('form.save()')
w('user.first_name = request.POST.get("first_name", user.first_name)')
w('user.last_name = request.POST.get("last_name", user.last_name)')
w('user.save(update_fields=["first_name", "last_name"])')
w('messages.success(request, "Profile updated successfully"); return redirect("profile")')
d()
d()
w('else: form = ProfileUpdateForm(instance=profile_obj)')
w('return render(request, "profile.html", {"form": form, "profile": profile_obj})')
d()
w('')
w('')
w('@login_required')
w('def my_bookings(request):')
i()
w('bookings = Booking.objects.filter(customer=request.user).select_related("hostel", "room").order_by("-booked_at")')
w('return render(request, "my_bookings.html", {"bookings": bookings})')
d()
w('')
w('')
w('# FAVORITES')
w('@login_required')
w('@require_http_methods(["POST"])')
w('def toggle_favorite(request):')
i()
w('try:')
i()
w('data = json.loads(request.body)')
w('hostel = get_object_or_404(Hostel, id=data.get("hostel_id"))')
w('fav, created = Favorite.objects.get_or_create(customer=request.user, hostel=hostel)')
w('if not created: fav.delete(); return JsonResponse({"favorited": False})')
w('return JsonResponse({"favorited": True})')
d()
w('except Exception as e: return JsonResponse({"error": str(e)}, status=400)')
d()
w('')
w('')
w('@login_required')
w('def my_favorites(request):')
i()
w('favorites = Favorite.objects.filter(customer=request.user).select_related("hostel")')
w('return render(request, "my_favorites.html", {"favorites": favorites})')
d()
w('')
w('')
w('# BOOKING CANCELLATION')
w('@login_required')
w('@require_http_methods(["POST"])')
w('def cancel_booking(request, booking_id):')
i()
w('try:')
i()
w('booking = get_object_or_404(Booking, id=booking_id, customer=request.user)')
w('if booking.booking_status in ["Checked In", "Checked Out"]:')
i()
w('return JsonResponse({"error": "Cannot cancel an active or completed booking"}, status=400)')
d()
w('if booking.booking_status == "Cancelled":')
i()
w('return JsonResponse({"error": "Booking is already cancelled"}, status=400)')
d()
w('booking.booking_status = "Cancelled"; booking.payment_status = "Refunded"')
w('booking.save(update_fields=["booking_status", "payment_status"])')
w('Notification.objects.create(user=request.user, title="Booking Cancelled", message=f"Booking {booking.booking_reference} cancelled.")')
w('return JsonResponse({"success": True, "message": "Booking cancelled successfully"})')
d()
w('except Exception as e: return JsonResponse({"error": str(e)}, status=400)')
d()
w('')
w('')
w('# NOTIFICATIONS')
w('@login_required')
w('def view_notifications(request):')
i()
w('notifications = Notification.objects.filter(user=request.user).order_by("-created_at")')
w('unread_count = notifications.filter(is_read=False).count()')
w('return render(request, "notifications.html", {"notifications": notifications, "unread_count": unread_count})')
d()
w('')
w('')
w('@login_required')
w('@require_http_methods(["GET"])')
w('def api_notifications(request):')
i()
w('notifications = Notification.objects.filter(user=request.user).order_by("-created_at")[:20]')
w('unread_count = Notification.objects.filter(user=request.user, is_read=False).count()')
w('return JsonResponse({')
w('"notifications": [{"id": str(n.id), "title": n.title, "message": n.message, "is_read": n.is_read, "created_at": n.created_at.isoformat()} for n in notifications],')
w('"unread_count": unread_count,')
w('})')
d()
w('')
w('')
w('@login_required')
w('@require_http_methods(["POST"])')
w('def mark_notification_read(request, notification_id):')
i()
w('try:')
i()
w('notification = get_object_or_404(Notification, id=notification_id, user=request.user)')
w('notification.is_read = True; notification.save()')
w('return JsonResponse({"success": True})')
d()
w('except Exception as e: return JsonResponse({"error": str(e)}, status=400)')
d()
w('')
w('')
w('@login_required')
w('@require_http_methods(["POST"])')

c:/Users/user/ehostelfinder/gen_views_p3.py
#!/usr/bin/env python3
"""Generate the complete views.py - Part 3: API endpoints and remaining views."""
import os, py_compile
os.chdir(r'c:\Users\user\ehostelfinder')

with open('hostels/views.py', 'r') as f:
    existing = f.read()

lines = existing.split('\n')
while lines and lines[-1] == '':
    lines.pop()

indent = 0
def w(s):
    if indent:
        lines.append('    ' * indent + s)
    else:
        lines.append(s)
def i(n=1):
    global indent; indent += n
def d(n=1):
    global indent; indent -= n

# === API ENDPOINTS ===
w('')
w('@require_http_methods(["GET"])')
w('def api_hostels(request):')
i()
w('city = request.GET.get("city", "")')
w('country = request.GET.get("country", "")')
w('room_type = request.GET.get("room_type", "")')
w('university = request.GET.get("university", "")')
w('min_price = request.GET.get("min_price", "")')
w('max_price = request.GET.get("max_price", "")')
w('hostels = Hostel.objects.all()')
w('if city: hostels = hostels.filter(city__icontains=city)')
w('if country: hostels = hostels.filter(country__icontains=country)')
w('if university: hostels = hostels.filter(university=university)')
w('if room_type: hostels = hostels.filter(rooms__room_type=room_type).distinct()')
w('if min_price:')
i()
w('try: hostels = hostels.filter(price__gte=float(min_price)).distinct()')
w('except: pass')
d()
w('if max_price:')
i()
w('try: hostels = hostels.filter(price__lte=float(max_price)).distinct()')
w('except: pass')
d()
w('results = []')
w('for h in hostels:')
i()
w('cover = h.images.filter(is_cover=True).first()')
w('results.append({"id": str(h.id), "name": h.name, "city": h.city, "country": h.country, "university": h.university, "address": h.address, "description": h.description, "average_rating": round(float(h.average_rating), 2), "rating": float(h.rating) if h.rating else round(float(h.average_rating), 2), "review_count": h.reviews.count(), "image_url": h.image_url or (cover.image_url if cover else None), "facilities": [f.facility_name for f in h.facilities.all()], "amenities": h.amenities or [], "check_in_time": h.check_in_time.strftime("%H:%M") if h.check_in_time else "14:00", "check_out_time": h.check_out_time.strftime("%H:%M") if h.check_out_time else "11:00", "distance": h.distance or "", "price": float(h.price) if h.price else 0, "contact": h.contact or "", "available": h.available})')
d()
w('return JsonResponse(results, safe=False)')
d()
w('')
w('@require_http_methods(["GET"])')
w('def api_hostel_detail(request, id):')
i()
w('hostel = get_object_or_404(Hostel, id=id)')
w('rooms = Room.objects.filter(hostel=hostel)')
w('cover = hostel.images.filter(is_cover=True).first()')
w('rooms_data = [{"id": str(r.id), "room_number": r.room_number, "room_name": r.room_name, "room_type": r.room_type, "capacity": r.capacity, "price_per_night": str(r.price_per_night), "description": r.description, "private_bathroom": r.private_bathroom, "air_conditioning": r.air_conditioning, "wifi": r.wifi, "status": r.status} for r in rooms]')
w('return JsonResponse({"id": str(hostel.id), "name": hostel.name, "description": hostel.description, "address": hostel.address, "city": hostel.city, "country": hostel.country, "phone": hostel.phone, "email": hostel.email, "latitude": str(hostel.latitude) if hostel.latitude else None, "longitude": str(hostel.longitude) if hostel.longitude else None, "image_url": cover.image_url if cover else None, "rooms": rooms_data, "facilities": [{"name": f.facility_name} for f in hostel.facilities.all()]})')
d()
w('')
w('@require_http_methods(["GET"])')
w('def api_cities(request):')
i()
w('return JsonResponse(sorted(Hostel.objects.values_list("city", flat=True).exclude(city="").distinct()), safe=False)')
d()
w('')
w('@require_http_methods(["GET"])')
w('def api_countries(request):')
i()
w('return JsonResponse(sorted(Hostel.objects.values_list("country", flat=True).exclude(country="").distinct()), safe=False)')
d()
w('')
w('@require_http_methods(["GET", "POST"])')
w('def login(request):')
i()
w('if request.method == "GET":')
i()
w('return render(request, "login.html", {"form": UserLoginForm()})')
d()
w('form = UserLoginForm(request.POST)')
w('if form.is_valid():')
i()
w('from django.contrib.auth import authenticate, login as auth_login')
w('user = authenticate(request, username=form.cleaned_data["email"], password=form.cleaned_data["password"])')
w('if user:')
i()
w('auth_login(request, user)')
w('return redirect("home")')
d()
w('messages.error(request, "Invalid email or password")')
d()
w('else:')
i()
w('messages.error(request, "Invalid email or password")')
d()
w('return render(request, "login.html", {"form": form})')
d()
w('')
w('@require_http_methods(["GET", "POST"])')
w('def signup(request):')
i()
w('if request.method == "POST":')
i()
w('form = UserRegistrationForm(request.POST)')
w('if form.is_valid():')
i()
w('user = form.save()')
w('try:')
i()
w('from .email_utils import send_email_confirmation')
w('send_email_confirmation(user, request)')
d()
w('except: pass')
d()
w('messages.success(request, "Account created! Please check your email to confirm.")')
w('return redirect("login")')
d()
w('else:')
i()
w('form = UserRegistrationForm()')
d()
w('return render(request, "signup.html", {"form": form})')
d()
w('')
w('@require_http_methods(["GET"])')
w('def logout_view(request):')
i()
w('logout(request); return redirect("home")')
d()
w('')
w('def cookie_policy(request): return render(request, "cookie_policy.html")')
w('def privacy_policy(request): return render(request, "privacy_policy.html")')
w('def terms_of_use(request): return render(request, "terms_of_use.html")')
w('def ai_assistant(request): return render(request, "ai_assistant.html")')
w('def how_it_works(request): return render(request, "how_it_works.html")')
w('')
w('@require_http_methods(["GET"])')
w('def admin_messages(request):')
i()
w('if not request.user.is_authenticated: return JsonResponse({"error": "Auth required"}, status=401)')
w('msgs = ContactMessage.objects.all()[:100]')
w('return JsonResponse({"messages": [{"id": msg.id, "full_name": msg.full_name, "email": msg.email, "subject": msg.subject, "message": msg.message, "created_at": msg.created_at.isoformat(), "is_read": msg.is_read} for msg in msgs]})')
d()
w('')
w('@require_http_methods(["GET", "POST"])')
w('def get_user(request):')
i()
w('if request.user.is_authenticated:')
i()
w('p = getattr(request.user, "profile", None)')
