import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'ehostelfinder.settings')
django.setup()

from hostels.models import Hostel

# Popular universities around Kampala with sample hostels
universities_hostels = [
    {
        'university': 'Makerere University',
        'hostel': 'University Hall Hostel',
        'description': 'Cozy hostel right at the heart of Makerere University campus. Perfect for students looking for convenience and community.',
        'distance': '0 km (On campus)',
        'price': 350000,
        'rating': 4.8,
        'review_count': 127,
        'image_url': 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop',
        'amenities': ['WiFi', 'Security', 'Study Rooms', 'Laundry', 'Common Area'],
        'contact': '+256 700 123456',
        'address': 'Makerere University Main Campus, Kampala',
    },
    {
        'university': 'Makerere University',
        'hostel': 'Complex Hall Residence',
        'description': 'Modern accommodation facility with en-suite rooms and 24-hour security. Walking distance to all faculties.',
        'distance': '0 km (On campus)',
        'price': 450000,
        'rating': 4.6,
        'review_count': 89,
        'image_url': 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop',
        'amenities': ['WiFi', 'Security', 'Parking', 'Laundry', 'Gym'],
        'contact': '+256 700 234567',
        'address': 'Complex hostels, Makerere University',
    },
    {
        'university': 'Makerere University Business School (MUBS)',
        'hostel': 'MUBS Campus View Hostel',
        'description': 'Affordable hosting with stunning views of the MUBS campus. Quiet environment ideal for studying.',
        'distance': '0 km (On campus)',
        'price': 300000,
        'rating': 4.4,
        'review_count': 76,
        'image_url': 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop',
        'amenities': ['WiFi', 'Security', 'Study Areas', 'Kitchen'],
        'contact': '+256 700 345678',
        'address': 'MUBS Campus, Nakawa, Kampala',
    },
    {
        'university': 'Makerere University Business School (MUBS)',
        'hostel': 'Nakawa Student Homes',
        'description': 'Fully furnished rooms with shared common spaces. Located just a 5-minute walk from MUBS main gate.',
        'distance': '0.5 km from MUBS',
        'price': 280000,
        'rating': 4.2,
        'review_count': 54,
        'image_url': 'https://images.unsplash.com/photo-1484154218962-a197022b85ba?w=800&h=600&fit=crop',
        'amenities': ['WiFi', 'Security', 'Kitchen', 'Laundry'],
        'contact': '+256 700 456789',
        'address': 'Nakawa, Kampala',
    },
    {
        'university': 'Kyambogo University',
        'hostel': 'Kyambogo University Hostels',
        'description': 'Official university hostels with strict security and clean facilities. Meals available on request.',
        'distance': '0 km (On campus)',
        'price': 250000,
        'rating': 4.5,
        'review_count': 203,
        'image_url': 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop',
        'amenities': ['WiFi', 'Security', 'Mess Hall', 'Sports Facilities'],
        'contact': '+256 700 567890',
        'address': 'Kyambogo University Main Campus',
    },
    {
        'university': 'Kyambogo University',
        'hostel': 'Banda Heights Residence',
        'description': 'Modern private hostel near Kyambogo University. Offers both single and double room options.',
        'distance': '1 km from Kyambogo',
        'price': 320000,
        'rating': 4.7,
        'review_count': 98,
        'image_url': 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop',
        'amenities': ['WiFi', 'Security', 'Parking', 'Water Tank', 'Solar'],
        'contact': '+256 700 678901',
        'address': 'Banda, Kyambogo',
    },
    {
        'university': 'Uganda Christian University (UCU)',
        'hostel': 'UCU Mukono Hostel',
        'description': 'Peaceful Christian-based accommodation within walking distance to UCU. Great for students seeking a serene environment.',
        'distance': '0 km (Near UCU)',
        'price': 270000,
        'rating': 4.6,
        'review_count': 145,
        'image_url': 'https://images.unsplash.com/photo-1600596542815-ee31c0995bec?w=800&h=600&fit=crop',
        'amenities': ['WiFi', 'Security', 'Reading Rooms', 'Laundry'],
        'contact': '+256 700 789012',
        'address': 'UCU Campus, Mukono',
    },
    {
        'university': 'Uganda Christian University (UCU)',
        'hostel': 'Mukono Student Center',
        'description': 'Modern furnished rooms with reliable power and water supply. Close to shops and transport.',
        'distance': '0.8 km from UCU',
        'price': 300000,
        'rating': 4.3,
        'review_count': 67,
        'image_url': 'https://images.unsplash.com/photo-1615529162924-f8605388463a?w=800&h=600&fit=crop',
        'amenities': ['WiFi', 'Security', 'Water Tank', 'Generator'],
        'contact': '+256 700 890123',
        'address': 'Mukono Town, near UCU',
    },
    {
        'university': 'Uganda Martyrs University (UMU)',
        'hostel': 'UMU Campus Accommodation',
        'description': 'Comfortable rooms within the UMU campus premises. Safe and secure with regular maintenance.',
        'distance': '0 km (On campus)',
        'price': 220000,
        'rating': 4.4,
        'review_count': 112,
        'image_url': 'https://images.unsplash.com/photo-1584622050111-993a426fbf0a?w=800&h=600&fit=crop',
        'amenities': ['WiFi', 'Security', 'Library Access', 'Sports'],
        'contact': '+256 700 901234',
        'address': 'UMU Campus, Nkozi',
    },
    {
        'university': 'Uganda Martyrs University (UMU)',
        'hostel': 'Nkozi Student Lodge',
        'description': 'Affordable private lodging just 10 minutes walk from UMU main gate. Includes breakfast.',
        'distance': '0.8 km from UMU',
        'price': 180000,
        'rating': 4.0,
        'review_count': 45,
        'image_url': 'https://images.unsplash.com/photo-1595576508898-0ad5c879a061?w=800&h=600&fit=crop',
        'amenities': ['WiFi', 'Security', 'Meals', 'Laundry'],
        'contact': '+256 700 012345',
        'address': 'Nkozi Town, Mpigi District',
    },
    {
        'university': 'Nkumba University',
        'hostel': 'Nkumba University Halls',
        'description': 'On-campus hostels with a vibrant student community. Perfect for first-year students.',
        'distance': '0 km (On campus)',
        'price': 200000,
        'rating': 4.2,
        'review_count': 178,
        'image_url': 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop',
        'amenities': ['WiFi', 'Security', 'Cafeteria', 'Common Rooms'],
        'contact': '+256 700 112233',
        'address': 'Nkumba University Campus, Entebbe',
    },
    {
        'university': 'Nkumba University',
        'hostel': 'Entebbe Road Residences',
        'description': 'Quality accommodation along Entebbe road with reliable transport to Nkumba University.',
        'distance': '3 km from Nkumba',
        'price': 240000,
        'rating': 4.1,
        'review_count': 62,
        'image_url': 'https://images.unsplash.com/photo-1560185007-5f0bb1866cab?w=800&h=600&fit=crop',
        'amenities': ['WiFi', 'Security', 'Parking', 'Generator'],
        'contact': '+256 700 223344',
        'address': 'Nkumba, Entebbe Road',
    },
    {
        'university': 'International University of East Africa (IUEA)',
        'hostel': 'IUEA Student Homes',
        'description': 'Modern hostels designed for international standards. Perfect for both local and international students.',
        'distance': '0 km (On campus)',
        'price': 380000,
        'rating': 4.7,
        'review_count': 91,
        'image_url': 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&h=600&fit=crop',
        'amenities': ['WiFi', 'Security', 'AC', 'Gym', 'Cafeteria'],
        'contact': '+256 700 334455',
        'address': 'IUEA Campus, Kansanga, Kampala',
    },
    {
        'university': 'International University of East Africa (IUEA)',
        'hostel': 'Kansanga Luxury Rooms',
        'description': 'Premium accommodation with modern finishing. Includes concierge services and 24/7 support.',
        'distance': '0.5 km from IUEA',
        'price': 420000,
        'rating': 4.8,
        'review_count': 56,
        'image_url': 'https://images.unsplash.com/photo-1595899818659-9b2c9d4f7a1a?w=800&h=600&fit=crop',
        'amenities': ['WiFi', 'Security', 'AC', 'Laundry', 'Gym', 'TV Room'],
        'contact': '+256 700 445566',
        'address': 'Kansanga, Kampala',
    },
    {
        'university': 'Ndejje University',
        'hostel': 'Ndejje University Hostels',
        'description': 'Spacious rooms with clean facilities. The university provides a safe Christian learning environment.',
        'distance': '0 km (On campus)',
        'price': 280000,
        'rating': 4.3,
        'review_count': 134,
        'image_url': 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop',
        'amenities': ['WiFi', 'Security', 'Sports Fields', 'Cafeteria'],
        'contact': '+256 700 556677',
        'address': 'Ndejje University Main Campus',
    },
    {
        'university': 'Ndejje University',
        'hostel': 'Mengo Student Lodge',
        'description': 'Conveniently located hostel with easy access to Ndejje University. Includes study tables and reading lights.',
        'distance': '2 km from Ndejje',
        'price': 260000,
        'rating': 4.1,
        'review_count': 78,
        'image_url': 'https://images.unsplash.com/photo-1590202096774-2b01435a422c?w=800&h=600&fit=crop',
        'amenities': ['WiFi', 'Security', 'Study Tables', 'Water Tank'],
        'contact': '+256 700 667788',
        'address': 'Mengo Hill, Kampala',
    },
]

count = 0
for data in universities_hostels:
    hostel, created = Hostel.objects.get_or_create(
        name=data['hostel'],
        university=data['university'],
        defaults={
            'description': data['description'],
            'distance': data['distance'],
            'price': data['price'],
            'rating': data['rating'],
            'review_count': data['review_count'],
            'image_url': data['image_url'],
            'amenities': data['amenities'],
            'contact': data['contact'],
            'address': data['address'],
            'available': True,
        }
    )
    if created:
        count += 1
        print(f"✓ Created: {hostel.name} ({hostel.university})")
    else:
        print(f"✗ Already exists: {hostel.name}")

print(f"\n✅ Added {count} new hostels")
print(f"Total hostels in DB: {Hostel.objects.count()}")
print(f"Universities: {list(Hostel.objects.values_list('university', flat=True).distinct())}")
