#!/usr/bin/env python3
"""Write the complete views.py file for EHostelFinder."""

import os
os.chdir('c:/Users/user/ehostelfinder')

lines = []

def L(s, indent=0):
    if indent:
        s = '    ' * indent + s
    lines.append(s)

# Imports
L('from django.shortcuts import render, get_object_or_404, redirect')
L('from django.contrib.auth import logout')
L('from django.http import JsonResponse')
L('from django.views.decorators.http import require_http_methods')
L('from django.views.decorators.csrf import csrf_exempt')
L('from django.contrib import messages')
L('from django.db.models import Avg')
L('from django.core.paginator import Paginator')
L('from django.utils import timezone')
L('from django.contrib.auth.decorators import login_required')
L('import json, os, urllib.request, urllib.error, uuid')
L('from .forms import UserRegistrationForm, UserLoginForm, ForgotPasswordForm, ResetPasswordForm, ProfileUpdateForm, HostelUploadForm')
L('from .models import Hostel, User, ContactMessage, Profile, Room, Booking, Review, Favorite, Message, Notification, Payment, RoomStatus, BookingStatus')
L('from .local_ai import get_local_ai_response')
L('')

# KAMPALA_AREA_UNIVERSITIES
L("KAMPALA_AREA_UNIVERSITIES = ['Makerere University', 'Makerere University Business School', 'Kyambogo University', 'Kampala International University', 'Uganda Christian University', 'Ndejje University', 'Bugema University', 'Cavendish University Uganda', 'St. Lawrence University Uganda', 'Mutesa I Royal University']")
L('')

# get_university_options
L('def get_university_options():')
L('    university_names, seen = [], set()')
L('    def normalize(name):')
L('        if not name: return ""')
L('        n = name.strip().lower()')
L("        if 'makerere' in n and 'business school' in n: return 'Makerere University Business School'")
L("        if 'makerere' in n: return 'Makerere University'")
L("        return name.strip()")
L("    for name in KAMPALA_AREA_UNIVERSITIES + list(Hostel.objects.exclude(university='').values_list('university', flat=True)):")
L("        if name:")
L("            normalized = normalize(name)")
L("            if normalized.lower() not in seen:")
L("                university_names.append(normalized)")
L("                seen.add(normalized.lower())")
L("    return [{'name': n} for n in university_names]")
L('')

# home
L('def home(request):')
L("    university = request.GET.get('university', 'All Universities')")
L("    city = request.GET.get('city', '')")
L("    country = request.GET.get('country', '')")
L("    min_price = request.GET.get('min_price', '')")
L("    max_price = request.GET.get('max_price', '')")
L("    sort_by = request.GET.get('sort', '-created_at')")
L("    page = request.GET.get('page', 1)")
L("    valid_sorts = ['name', '-name', 'price', '-price', 'rating', '-rating', 'created_at', '-created_at']")
L("    if sort_by not in valid_sorts: sort_by = '-created_at'")
L("    hostels = Hostel.objects.all()")
L("    if university and university != 'All Universities': hostels = hostels.filter(university=university)")
L("    if city: hostels = hostels.filter(city__icontains=city)")
L("    if country: hostels = hostels.filter(country__icontains=country)")
L("    if min_price:")
L("        try: hostels = hostels.filter(price__gte=float(min_price)).distinct()")
L("        except ValueError: pass")
L("    if max_price:")
L("        try: hostels = hostels.filter(price__lte=float(max_price)).distinct()")
L("        except ValueError: pass")
L("    hostels = hostels.order_by(sort_by)")
L("    paginator = Paginator(hostels, 12)")
L("    try: page_obj = paginator.page(page)")
L("    except: page_obj = paginator.page(1)")
L("    cities_list = sorted(Hostel.objects.values_list('city', flat=True).exclude(city='').distinct())")
L("    countries_list = sorted(Hostel.objects.values_list('country', flat=True).exclude(country='').distinct())")
L("    universities = get_university_options()")
L("    rated_hostels = Hostel.objects.exclude(rating__isnull=True)")
L("    avg_rating = round(sum(float(h.rating) for h in rated_hostels) / rated_hostels.count(), 1) if rated_hostels.exists() else 0.0")
L("    hostel_list = []")
L("    for h in page_obj:")
L("        cover = h.images.filter(is_cover=True).first()")
L("        available_room = h.rooms.filter(status='Available').first()")
L("        hostel_list.append({")
L("            'id': str(h.id), 'name': h.name, 'description': h.description, 'city': h.city, 'country': h.country,")
L("            'university': h.university, 'image_url': h.image_url or (cover.image_url if cover else None),")
L("            'facilities': [{'name': f.facility_name, 'icon': f.icon or ''} for f in h.facilities.all()],")
L("            'available': h.available, 'rating': float(h.rating) if h.rating else round(float(h.average_rating), 1),")
L("            'distance': h.distance or 'Near campus',")
L("            'price': str(h.price) if h.price else (str(available_room.price_per_night) if available_room else '0'),")
L("            'amenities': h.amenities or [],")
L("        })")
L("    favorite_ids = []")
L("    if request.user.is_authenticated:")
L("        favorite_ids = list(Favorite.objects.filter(customer=request.user).values_list('hostel_id', flat=True))")
L("    return render(request, 'home.html', {")
L("        'hostels': hostel_list, 'cities': cities_list, 'countries': countries_list, 'universities': universities,")
L("        'selected_city': city, 'selected_country': country, 'selected_university': university, 'selected_sort': sort_by,")
L("        'total_hostels': Hostel.objects.count(), 'total_universities': len(universities), 'avg_rating': avg_rating,")
L("        'total_cities': len(cities_list), 'page_obj': page_obj, 'favorite_ids': [str(fid) for fid in favorite_ids],")
L("    })")
L('')

# hostel_detail
L('def hostel_detail(request, id):')
L('    try:')
L('        hostel = get_object_or_404(Hostel, id=id)')
L("        rooms = Room.objects.filter(hostel=hostel, status='Available').order_by('floor', 'room_number')")
L('        images = hostel.images.all()')
L('        cover = hostel.images.filter(is_cover=True).first()')
L('        facilities = hostel.facilities.all()')
L("        reviews = hostel.reviews.select_related('customer').all()")
L('        floors = {}')
L('        for r in rooms:')
L('            fn = r.floor or 1')
L("            if fn not in floors: floors[fn] = []")
L('            floors[fn].append(r)')
L('        floors_data = []')
L('        for fn in sorted(floors.keys()):')
L('            floors_data.append({"floor_number": fn, "rooms": [{"id": str(r.id), "room_number": r.room_number, "room_name": r.room_name, "room_type": r.room_type, "price_per_night": str(r.price_per_night), "status": r.status, "is_available": r.is_available, "capacity": r.capacity} for r in floors[fn]]})')
L('        rooms_data = []')
L('        for r in rooms:')
L('            rooms_data.append({')
L("                'id': str(r.id), 'room_number': r.room_number, 'room_name': r.room_name, 'room_type': r.room_type,")
L("                'capacity': r.capacity, 'available_quantity': r.available_quantity, 'price_per_night': str(r.price_per_night),")
L("                'floor': r.floor or 1, 'description': r.description,")
L("                'private_bathroom': r.private_bathroom, 'air_conditioning': r.air_conditioning,")
L("                'balcony': r.balcony, 'television': r.television, 'wifi': r.wifi,")
L("                'images': [ri.image_url for ri in r.images.all()],")
L('            })')
L('        reviews_data = []')
L('        for rv in reviews:')
L('            reviews_data.append({')
L("                'id': str(rv.id), 'customer_name': rv.customer.get_full_name() or rv.customer.email,")
L("                'rating': rv.rating, 'comment': rv.comment, 'created_at': rv.created_at.strftime('%Y-%m-%d'),")
L('            })')
L('        context = {')
L("            'hostel': {")
L("                'id': str(hostel.id), 'name': hostel.name, 'description': hostel.description,")
L("                'address': hostel.address, 'city': hostel.city, 'country': hostel.country,")
L("                'university': hostel.university, 'distance': hostel.distance or 'Near campus',")
L("                'price': float(hostel.price) if hostel.price else 0,")
L("                'rating': float(hostel.rating) if hostel.rating else round(float(hostel.average_rating), 1),")
L("                'available': hostel.available, 'contact': hostel.contact or '',")
L("                'amenities': hostel.amenities or [], 'phone': hostel.phone, 'email': hostel.email,")
L("                'latitude': str(hostel.latitude) if hostel.latitude else None,")
L("                'longitude': str(hostel.longitude) if hostel.longitude else None,")
L("                'cover_image': cover.image_url if cover else None,")
L("                'images': [{'url': img.image_url, 'is_cover': img.is_cover} for img in images],")
L('            },')
L("            'rooms': rooms_data, 'facilities': [{'name': f.facility_name, 'icon': f.icon or ''} for f in facilities],")
L("            'reviews': reviews_data, 'floors': json.dumps(floors_data),")
L('        }')
L('    except Exception as e:')
L("        print(f'Error in hostel_detail: {e}')")
L("        messages.error(request, 'Error loading hostel details')")
L("        return redirect('home')")
L('')
L("    if request.method == 'POST' and 'review_submit' in request.POST:")
L('        if not request.user.is_authenticated:')
L("            messages.error(request, 'You must be logged in to leave a review')")
L("            return redirect('login')")
L("        rating = request.POST.get('rating', '').strip()")
L("        comment = request.POST.get('comment', '').strip()")
L("        if not rating or not rating.isdigit() or int(rating) not in range(1, 6):")
L("            messages.error(request, 'Please select a valid rating from 1 to 5.')")
L("            return redirect('hostel_detail', id=hostel.id)")
L('        Review.objects.create(hostel=hostel, customer=request.user, rating=int(rating), comment=comment)')
L('        hostel.review_count = hostel.reviews.count()')
L("        hostel.rating = round(hostel.reviews.aggregate(avg=Avg('rating'))['avg'] or 0, 2)")
L("        hostel.save(update_fields=['review_count', 'rating'])")
L("        messages.success(request, 'Your review has been submitted successfully.')")
L("        return redirect('hostel_detail', id=hostel.id)")
L('    return render(request, \'hostel_detail.html\', context)')
L('')

# Write file
with open('hostels/views.py', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f"Wrote {len(lines)} lines to hostels/views.py")

# Verify no syntax errors
import py_compile
try:
    py_compile.compile('hostels/views.py', doraise=True)
    print("Syntax check: PASSED")
except py_compile.PyCompileError as e:
    print(f"Syntax check FAILED: {e}")
