# Generated by Django 6.0.4 on 2026-04-28 15:31

import hostels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=hostels.models.generate_user_id, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
