# Generated by Django 6.0.3 on 2026-07-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0009_chatmessage_is_ai_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='room_label_range',
            field=models.JSONField(blank=True, default=dict, help_text='Stores room label type, start, end, and floor count'),
        ),
    ]
