# Generated by Django 6.0.3 on 2026-07-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0010_hostel_room_label_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='flutterwave_method',
            field=models.CharField(blank=True, help_text='Specific Flutterwave payment method', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='flw_ref',
            field=models.CharField(blank=True, help_text='Flutterwave reference', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe Payment Intent ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer'), ('Mobile Money', 'Mobile Money'), ('Account', 'Account'), ('USSD', 'USSD'), ('Enaira', 'Enaira'), ('Apple Pay', 'Apple Pay'), ('Google Pay', 'Google Pay')], max_length=20),
        ),
    ]
