# Generated by Django 6.0.3 on 2026-07-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0011_payment_flutterwave_method_payment_flw_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='is_full',
            field=models.BooleanField(default=False, help_text='Set to True when all rooms are occupied'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='total_floors',
            field=models.PositiveIntegerField(default=1, help_text='Total number of floors in the building'),
        ),
    ]
